### ISSUE TITLE
MacOS Catalina won’t boot using EFI 3.0.3

### ISSUE THREAD

**Issue by hewad23** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#101]
I have been using efi 3.0.2 OC 0.5.7 without any issue but recently i tried to update to OC 0.5.9 and i took the acpi files and oc-config.plist from efi 3.0.3 and the driver and kext files from the efi-3.0.2. I am not sure what i am doing wrong. Do you have complete efi for version 0.5.9 or 0.6.0 opencore. I have lenovo Y540. 

![image](https://user-images.githubusercontent.com/67558341/85972553-4e6da000-b99e-11ea-8252-e29957585c28.jpeg)

**Comment by xiaoMGitHub** [comment]
I plan to update the compatibility with macOS Big Sur next time, and currently 3.0.2 still meets daily use.It is expected that OC 0.6.0 will be updated after its official release.

**Comment by hewad23** [comment]
Thanks again for the hard work and will wait for the next release.

**Comment by hewad23** [comment]
> I plan to update the compatibility with macOS Big Sur next time, and currently 3.0.2 still meets daily use.It is expected that OC 0.6.0 will be updated after its official release.

Thank you for replying and for your hard work. We can’t wait for the next update. Thank you !!!
