### ISSUE TITLE
The OC 3.0.2-EFI folder - Language Chinese only

### ISSUE THREAD

**Issue by hewad23** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#102]
My windows drive wouldn’t boot but i had to install windows again but it also wiped my Macintosh hd too using recovery usb. Both has separate hard disk and i am not sure why. Anyways I made a bootable macos installation usb and used OC 3.0.2 efi but upon installation it doesn’t let me to pick a language and all installation was in Chinese. Im sorry i can’t read it but do you know the solution to this?

**Comment by xiaoMGitHub** [comment]
Set [prev-lang:kbd](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/blob/5a47e0f3e0f75f85c4d1e164ac45d2b5ff217f39/config-OpenCore.plist#L976) to empty.The default installation language is English.
