### ISSUE TITLE
触摸板不能使用

### ISSUE THREAD

**Issue by piscean18** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#103]
y7000 2019版，clover引导成功后，触摸板不能使用，鼠标左键双击不能使用，其他功能正常，是什么原因？应该检查哪里？

**Comment by xiaoMGitHub** [comment]
触控板问题，建议认真遇到EFI使用说明；鼠标问题建议更换鼠标，你鼠标坏了

**Comment by piscean18** [comment]
😂鼠标应该没有坏，左键右键单击都没问题，就左键单击有问题

**Comment by piscean18** [comment]
鼠标应该没有坏，左键右键单击都没问题，就左键双击不能使用
