### ISSUE TITLE
Can't have access to QQ

### ISSUE THREAD

**Issue by nicorazon4** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#104]
Hello im french and i can’t sign up on QQ because my phone number is invalid 
Can y have the EFI folder ?

**Comment by xiaoMGitHub** [comment]
The latest version is v3.0.2 and can be downloaded on the[ release page](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2).

**Comment by nicorazon4** [comment]
I past the EFI folder from OC_0.5.7
I past ACPI folder from source code
After i replace the config.plist from source code
But when i boot on the USB i have the following error : 
![Uploading 1AD36792-B135-4C49-A10F-67783F0200A6.jpeg…]()

**Comment by nicorazon4** [comment]
I past the EFI folder from OC_0.5.7
I past ACPI folder from source code
After i replace the config.plist from source code
But when i boot on the USB i have the following error : 
![E4EFCF25-B967-47AD-A8AA-1FC5F3DD0432](https://user-images.githubusercontent.com/33788345/86575768-11924200-bf78-11ea-87d3-7d49cfa11bd9.jpeg)

**Comment by xiaoMGitHub** [comment]
Direct file replacement is not supported.

**Comment by nicorazon4** [comment]
What is supported ?
