### ISSUE TITLE
Not any issue but a request.

### ISSUE THREAD

**Issue by hewad23** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#105]
Can you share complete OC EFI for MacOS Big Sur. I have Lenovo Legion Y540, I appreciate your hard work as in the past, in present and future. I know you are going to release it when OC 0.6.0 officially releases but can you at least guide me through. I will make sure to contribute towards your hard work. Thank You.

**Comment by xiaoMGitHub** [comment]
I do not use the beta version, and MacOS Big Sur related updates will be supported after the official version is released.

**Comment by hewad23** [comment]
> I do not use the beta version, and MacOS Big Sur related updates will be supported after the official version is released.

Thank you again and i will wait. Are you going to release it publicly or is there another group so i can join.

**Comment by madness786** [comment]
Please A requeat . i have Lenovo Y540 wiht i5 CPU . I need to install Catalina . Can you share a tutorial . Much appreciated . Thanks

**Comment by hewad23** [comment]
> Please A requeat . i have Lenovo Y540 wiht i5 CPU . I need to install Catalina . Can you share a tutorial . Much appreciated . Thanks 

Well there is a guide on youtube search for your laptop and you will see it and you would need EFI folder and that you will find it in GitHub.

**Comment by kodidono** [comment]
when installed with opencore bootloader, all menus are in Chinese, :) and there is no language choice :(
at first I can change the language, but then on the second reboot when installing the system, the language becomes Chinese again.. it can be changed only after complete installation of the system.
please return the language selection
Of course, thank you very much for your work!

**Comment by xiaoMGitHub** [comment]
> when installed with opencore bootloader, all menus are in Chinese, :) and there is no language choice :(
> at first I can change the language, but then on the second reboot when installing the system, the language becomes Chinese again.. it can be changed only after complete installation of the system.
> please return the language selection
> Of course, thank you very much for your work!

Set prev-lang:kbd to empty.The default installation language is English.

**Comment by kodidono** [comment]
what do you think about card intel wi-fi? are you planning to add it?
https://www.tonymacx86.com/threads/success-working-intel-wifi-drivers-for-7265ac-on-catalina.292207/page-73
