### ISSUE TITLE
Tutorial on how to install catalina on Lenovo Legion y540 with I5 cpu 

### ISSUE THREAD

**Issue by madness786** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#106]
I am new to hackintosh  . Can you please make a step by step turotial on how to make a working hackintosh out of lenoto legion y540 i5 9th gen cpu :) .

Best Regard 
 I will keep waiting

**Comment by xiaoMGitHub** [comment]
[Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/)

**Comment by madness786** [comment]
> [Booting the OS X installer on LAPTOPS with Clover](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/)

:( :( :(  I really got no clue about this .. please can you a tutorial for me brother. I do not have acess to mac books .. a tutorial on windows 10 . thanks in advance bro

**Comment by xiaoMGitHub** [comment]
[Learning Chinese well seems to be a good choice.](https://space.bilibili.com/188733433)

**Comment by madness786** [comment]
> [Learning Chinese well seems to be a good choice.](https://space.bilibili.com/188733433)

Ni hao . Wo jiao zhu xiao dan . wo shi yindu ren .. i lived in china for 6 years gege . wo shi jilin daxue de xue sheng :) xie xie ni

**Comment by SohilK03** [comment]
I also need a tutorial on this ... pls help

**Comment by SohilK03** [comment]
@xiaoMGitHub Pls help
I want to use Hackintosh on same laptop but with different config :- 
1. I5 9th gen
2. gtx 1660
3. 8gb ram

**Comment by xiaoMGitHub** [comment]
> I also need a tutorial on this ... pls help

The above tutorial is generally applicable.

**Comment by madness786** [comment]
> > I also need a tutorial on this ... pls help
> 
> The above tutorial is generally applicable.

This tutorial Didn't work for me either.  Please can someone make a step by step tutorial :).  Thanks in advance .

**Comment by SohilK03** [comment]
@xiaoMGitHub it would be really helpful if you could make it or tell the major changes to make it work on our config.
