### ISSUE TITLE
3.0.3发布时间

### ISSUE THREAD

**Issue by Armsinrius** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#107]
您好,请问3.0.3版本什么时候会发布下载?
谢谢您

**Comment by xiaoMGitHub** [comment]
预计Mac OS 11正式版发布后两个星期内会上传EFI，目前3.0.2满足13.6-10.15.6的使用，没有必要对外进行更新

**Comment by Armsinrius** [comment]
那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？

**Comment by madness786** [comment]
> 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？

I too have similar issue . Its not working on my Lenovo Legion Y540 15 international Version .

Help is always requested

**Comment by xiaoMGitHub** [comment]
> 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？

相关的[配置文件](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/blob/master/config-Clover-2020%E6%AC%BE.plist)我已经在一个月前上传。

**Comment by xiaoMGitHub** [comment]
> > 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？
> 
> I too have similar issue . Its not working on my Lenovo Legion Y540 15 international Version .
> 
> Help is always requested

After testing, 3.0.2 supports Y540 to install MacOS 10.15.6.

**Comment by madness786** [comment]
> > > 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？
> > 
> > 
> > I too have similar issue . Its not working on my Lenovo Legion Y540 15 international Version .
> > Help is always requested
> 
> After testing, 3.0.2 supports Y540 to install MacOS 10.15.6.

I tried all hackintosh available over the internet. Nitesh Catalina , olarillo Catalina . No chance for me :( 

Please share 10.15.6  link. 

Much appreciated 🙏

**Comment by xiaoMGitHub** [comment]
[10.15.6](https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/)

**Comment by xiaoMGitHub** [comment]
> > > > 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？
> > > 
> > > 
> > > I too have similar issue . Its not working on my Lenovo Legion Y540 15 international Version .
> > > Help is always requested
> > 
> > 
> > After testing, 3.0.2 supports Y540 to install MacOS 10.15.6.
> 
> I tried all hackintosh available over the internet. Nitesh Catalina , olarillo Catalina . No chance for me :(
> 
> Please share 10.15.6 link.
> 
> Much appreciated 🙏

[10.15.6](https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/)

**Comment by Armsinrius** [comment]
> > 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？
> 
> 相关的[配置文件](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/blob/master/config-Clover-2020%E6%AC%BE.plist)我已经在一个月前上传。

你好我尝试了10.15.6在legion 5i上面安装,用你发的配置文件替换了原本3.0.2中的config.plist但是依然提示this version of mac OS X can not be install on this device.我也尝试了10.15.4也依然是相同的报错.请问可能是什么原因
谢谢

**Comment by Armsinrius** [comment]
> > 那想请问一下现在的可供下载的3.0.2支持2020款国际版legion 5i吗？
> 
> 相关的[配置文件](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/blob/master/config-Clover-2020%E6%AC%BE.plist)我已经在一个月前上传。

您好，除了替换配置文件config.plist还需要替换别的文件吗？还是需要把原来的配置文件也留着？
