### ISSUE TITLE
请问一下联想2018Y7000安装界面13.6版本，半个小时都没有动了

### ISSUE THREAD

**Issue by JohnnyZhang0628** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#108]
![微信图片_20200724101848](https://user-images.githubusercontent.com/28375774/88355470-49322400-cd97-11ea-992b-5b9de8d72bd8.jpg)
大佬，知道怎么回事吗？也不报错！

**Comment by JohnnyZhang0628** [comment]
已经解决了，谢谢

**Comment by madness786** [comment]
i have the same issue . stilll coudnt solve it . please help . 

i have lenovo legion y540 9th gen i5 with nvidia 1060 graphic card . 

If posssible help me with a tutorial 👍

**Comment by JohnnyZhang0628** [comment]
@madness786 
you need delete efi folder all file instead of over file.It's my solution,but i have anthoer problem.So i'm not sure that is it correct

**Comment by madness786** [comment]
> @madness786
> you need delete efi folder all file instead of over file.It's my solution,but i have anthoer problem.So i'm not sure that is it correct

I tried deleting files only and also Efi Folder too . but nothing worked for me

**Comment by JohnnyZhang0628** [comment]
@madness786 I first use the image of 13.6,it's not work.Then i use 15.6,it's ok.So i think that it's  maybe the version of image problem.You can try it.

**Comment by madness786** [comment]
Please share link of 15.6 you used :).  Thanks in advance .

**Comment by JohnnyZhang0628** [comment]
@madness786  15.6 image download url:https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/macOS%20Catalina%2010.15.6%2819G73%29%20Installer%20for%20Clover%205119%20and%20WEPE.dmg

**Comment by madness786** [comment]
> @madness786 15.6 image download url
> https://mirrors.dtops.cc/iso/MacOS/daliansky_macos/macOS%20Catalina%2010.15.6%2819G73%29%20Installer%20for%20Clover%205119%20and%20WEPE.dmg

Xie xie . Gege.
