### ISSUE TITLE
I7-10875H

### ISSUE THREAD

**Issue by sailcat-code** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#110]
请问3.0.2全系支持的配置文件能否支持I7-10875H的Y7000P型号？感谢

**Comment by xiaoMGitHub** [comment]
不支持，3.0.3会提供支持

**Comment by beijingrice** [comment]
等不及啦（捂脸）
我是2060 i7-10875H的y7000p，安装会有什么问题呢？

**Comment by xiaoMGitHub** [comment]
> 等不及啦（捂脸）
> 我是2060 i7-10875H的y7000p，安装会有什么问题呢？

应该除了独显其他都能驱动，是的，intel无线网卡也能驱动

**Comment by beijingrice** [comment]
刚刚用3.0.2安装mojave，打开-v，卡在
end randomseed
++++++++++++++
应该是内存控制器啥的还没适配吧

**Comment by xiaojia21190** [comment]
@beijingrice 这个是cfg没关吧
