### ISSUE TITLE
trackpad only read 2 fingers

### ISSUE THREAD

**Issue by xrokz** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#111]
when i want to use 3 or 4 fingers it doesn't work it only read 2
so if i swiped up with 4 fingers it will scroll up.

fix please ?

**Comment by xiaoMGitHub** [comment]
You can submit an issue to the developer of [voodooi2c](https://github.com/VoodooI2C/VoodooI2C).

**Comment by xrokz** [comment]
no one can help
