### ISSUE TITLE
Complete  efi folder

### ISSUE THREAD

**Issue by doghuang** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#112]
下载下来只有config和acpi文件，有没有kext内的驱动，或者能不能提供一下完整的efi文件夹🙏🏻🙏🏻🙏🏻

**Comment by xiaoMGitHub** [comment]
## 发布

最后发布的版本是 v3.0.2，前往 [Release Page](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases) 下载即可。

**Comment by doghuang** [comment]
a lot of thanks to u
