### ISSUE TITLE
Opencore Not Installing MacOS

### ISSUE THREAD

**Issue by Iphone5-RecoveryMode** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#116]
I have a Lenovo legion y7000 (2019) laptop, and when I replace the efi and boot, it goes to picker. But when I click 'MacOS Base Install', it briefly shows the apple log and then goes black, the fans get really loud for a period of about 10-20 seconds, and it reboots

any help?

**Comment by AntiqPeace** [comment]
@Iphone5-RecoveryMode are you installing Big Sur?

**Comment by Iphone5-RecoveryMode** [comment]
no
Catalina

**Comment by Iphone5-RecoveryMode** [comment]
does anyone know why?

**Comment by RaviKavaiya** [comment]
Try using clover

**Comment by hewad23** [comment]
Its your GPU creating this issue because its picking Nvidia instead of Intel. Go to bios and set your GPU to switchable instead of Discrete GPU.

**Comment by Iphone5-RecoveryMode** [comment]
thanks
