### ISSUE TITLE
Please Give EFI 3.0.3

### ISSUE THREAD

**Issue by innocentalone** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#118]
@xiaoMGitHub  I know that if we want to get EFI 3.0.3, we have to join QQ group.
But, we can't join it. Please give latest BIg Sur EFI here.

If you don't want to publish in Releases page, then please atleast upload it here. I want to use it.

**Comment by AntiqPeace** [comment]
@xiaoMGitHub I agree with @innocentalone . Why don't you give efi for big sur? Please give

**Comment by xiaoMGitHub** [comment]
Or you can create a telegram group to invite me.

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub Please join this link :pray:
https://t.me/joinchat/KHjNdhxzGoJ6h6-oj5DUSw

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub Please join this link:
https://t.me/legiony530macos

**Comment by AntiqPeace** [comment]
@xiaoMGitHub Please join the Telegram group created by @RaviKavaiya . We are there...

**Comment by vasu549** [comment]
can you share telegram group??

**Comment by AntiqPeace** [comment]
> can you share telegram group??

https://t.me/joinchat/KHjNdlAeJRpk_hLu2NuG5w

**Comment by indowebdeveloper** [comment]
@xiaoMGitHub may i invite you to a telegram group so you can share the 3.0.3 EFI ?

**Comment by LuckyCrack** [comment]
need 3.0.3 EFI above telegram link Expired. Cant join QQ
