### ISSUE TITLE
Broadcom BCM943602CS, but how?

### ISSUE THREAD

**Issue by md-siam** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#120]
How you installed Broadcom BCM943602CS on your laptop?

**Comment by xiaoMGitHub** [comment]
![image](https://user-images.githubusercontent.com/23020844/91942904-43ccdf80-ed2e-11ea-909f-f019ce610b09.png)

![image](https://user-images.githubusercontent.com/23020844/91942988-6c54d980-ed2e-11ea-99a9-6f79e7b2672b.png)

**Comment by md-siam** [comment]
Did you give up your M.2 slot for using Wi-Fi, you are using the default wifi slott?
