### ISSUE TITLE
Sleep Issues

### ISSUE THREAD

**Issue by AntiqPeace** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#123]
Hello @xiaoMGitHub I am facing sleep/wake issues on your latest EFI Beta OpenCore (3.0.3) on Big Sur (With Catalina as well).

After sleep, when I wake system, I just see a black screen and nothing happens.

Any solution??

**Comment by xiaoMGitHub** [comment]
Try to replace AAPL, ig-platform-id is 0009B3E.

**Comment by AntiqPeace** [comment]
@xiaoMGitHub I have tried this. But still the same issue :(

**Comment by xiaoMGitHub** [comment]
Below PciRoot(0x0)/Pci(0x2,0x0) only AAPL, ig-platform-id are reserved.

**Comment by AntiqPeace** [comment]
Hello @xiaoMGitHub I don't understand... Sorry.
Can you send latest config.plist file?
If you can't send here, please send in telegram

**Comment by xiaoMGitHub** [comment]
```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
<dict>
<key>AAPL,ig-platform-id</key>
<data>AACbPg==</data>
</dict>
```

**Comment by AntiqPeace** [comment]
Ok done

**Comment by ammi3** [comment]
> Below PciRoot(0x0)/Pci(0x2,0x0) only AAPL, ig-platform-id are reserved.

可以，10.15.6只保留AAPL和ig-platform-id已解决睡眠无法唤醒问题

**Comment by xiaoMGitHub** [comment]
> > Below PciRoot(0x0)/Pci(0x2,0x0) only AAPL, ig-platform-id are reserved.
> 
> 可以，10.15.6只保留AAPL和ig-platform-id已解决睡眠无法唤醒问题

后续所有的更新只会针对2020款进行特别适配，其他版本只提供进系统能力，自行调优
