### ISSUE TITLE
i5 10200H可以用吗？

### ISSUE THREAD

**Issue by TianSir854** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#127]
i5 10200H能用这个EFI文件吗？

**Comment by xiaoMGitHub** [comment]
可以

**Comment by TianSir854** [comment]
10.15.6可以用吗？

**Comment by TianSir854** [comment]
> 可以

10.15.6可以用吗？

**Comment by xiaoMGitHub** [comment]
13.6 - 11.0beta8 都能用

**Comment by TianSir854** [comment]
为啥么我刚买的拯救者y7000不能引导呢？

**Comment by Xhichn** [comment]
> 为啥么我刚买的拯救者y7000不能引导呢？

i5-10200H核显是GT 1，无法驱动

**Comment by xiaoMGitHub** [comment]
> > 为啥么我刚买的拯救者y7000不能引导呢？
> 
> i5-10200H核显是GT 1，无法驱动

 可以驱动的，群里机友都成功了

**Comment by Xhichn** [comment]
> > > 为啥么我刚买的拯救者y7000不能引导呢？
> > 
> > 
> > i5-10200H核显是GT 1，无法驱动
> 
> 可以驱动的，群里机友都成功了

请问能发一下EFI吗？学习一下。
xhichn@foxmail.com
多谢
