### ISSUE TITLE
i7-10750H - Legion 5i

### ISSUE THREAD

**Issue by rlfto** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#128]
请问3.0.2全系支持的配置文件能否支持I7-10750H的5i型号？感谢

**Comment by xiaoMGitHub** [comment]
3.0.3已经完美支持，后续会发布，等不及的建议加群自取，目前内测中

**Comment by LuckyCrack** [comment]
When is 3.0.3 releasing

**Comment by LoneFennecFoxy** [comment]
> When is 3.0.3 releasing

If you would read around you would've found that he said he's releasing it on Chinese New Year. That would be February 12th.
