### ISSUE TITLE
Touchpad(ELAN) lags really bad..... like 1 fps, worked fine on OC 0.5.7 and 0.5.9

### ISSUE THREAD

**Issue by OnMyZenith** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#133]
I know this is not an issue that belongs here and I apologize for that but I had no other way of reaching you and only your patches worked.
So I was trying to update to OC 0.6.2 on Catalina and built my own EFI from the ground up but just couldn't figure out the touchpad, I tried Voodoo DSDT patching which either didn't work or I screwed up, so in the end I just decided to copy your EFI's SSDT-I2C.aml and Kexts just like I did last time with my 0.5.9 upgrade but for some reason it's lags real hard. I would love to get some advise on this or just some direction to relevant sources.
Thanks
PS: Version of macOS is same so is the hardware it's just OC 0.5.9 to 0.6.2

**Comment by xiaoMGitHub** [comment]
Try to modify the content in SSDT-I2C.aml.

before
```
        Method (_INI, 0, NotSerialized)  // _INI: Initialize
        {
            If (_OSI ("Darwin"))
            {
                TPDM = Zero
                OSYS = 0x07DF
            }
        }
```
after
 ```
        Method (_INI, 0, NotSerialized)  // _INI: Initialize
        {
            If (_OSI ("Darwin"))
            {
               OSYS = 0x07DF
            }
        }
```

**Comment by OnMyZenith** [comment]
It's actually just like the after as you say...

**Comment by xiaoMGitHub** [comment]
Can't understand what you mean.

**Comment by OnMyZenith** [comment]
"TPDM = Zero" was never there

**Comment by OnMyZenith** [comment]
Actually I don't get any input with SSDT-I2C. aml + your kexts

I can only get a some laggy input if I add voodooinput. Kext to your kexts as plugin

**Comment by OnMyZenith** [comment]
Maybe I'll just give DSDT Patching another shot

**Comment by xiaoMGitHub** [comment]
I probably understand your question, this needs to be resolved by modifying the BIOS advanced mode.

**Comment by OnMyZenith** [comment]
Is that possible?
