### ISSUE TITLE
2020Y7000 i5-10200H 卡代码rootln

### ISSUE THREAD

**Issue by WuYinBQ** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#136]
i5-10200H 到底怎么安装黑苹果 群人太少了

**Comment by xiaoMGitHub** [comment]
疑问解答可以提 [issues](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/issues) 给我或者加入我的QQ群：1014806625(已满)、216384299(已满)、477839538(拒绝用爱发电)
