### ISSUE TITLE
拯救者y7000 i5-10200H

### ISSUE THREAD

**Issue by WuYinBQ** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#137]
拯救者y7000 i5-10200H的核显大概什么时候才能修复

**Comment by xiaoMGitHub** [comment]
建议提 [issues](https://github.com/acidanthera/bugtracker/issues) 给开发者

**Comment by WuYinBQ** [comment]
> 建议提[问题](https://github.com/acidanthera/bugtracker/issues)给开发者

可以麻烦你帮我问一下开发者吗 我用百度翻译成英文怪怪的 怕开发者不理解 谢谢

**Comment by WuYinBQ** [comment]
> 建议提[问题](https://github.com/acidanthera/bugtracker/issues)给开发者

有空的时候帮我问一下就可以了 谢谢
