### ISSUE TITLE
睡眠秒醒问题

### ISSUE THREAD

**Issue by FuLiTang** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#139]
大佬求解，2018版的，我用的是oc5.7,安装好后系统那一刻就可以睡眠，使用过几天后就不可以睡眠了，现在睡眠秒醒，请问我需要改什么

**Comment by xiaoMGitHub** [comment]
执行优化命令，或者排查秒醒原因，话说你这个0.5.7有点久了，现在都以加0.6.2

**Comment by FuLiTang** [comment]
> 执行优化命令，或者排查秒醒原因，话说你这个0.5.7有点久了，现在都以加0.6.2

**Comment by FuLiTang** [comment]
装了0.6.2，睡眠一会然后自动唤醒黑屏

**Comment by xiaoMGitHub** [comment]
毕竟你不是使用我的EFI，建议自行排查下日志，目前没有群友反馈存在睡眠问题

**Comment by FuLiTang** [comment]
是是用你的efi，一个是从你的库下载，另外一个0.6.2是从你的群使用，我自己排查下日志。谢谢大佬了

**Comment by xiaoMGitHub** [comment]
是群友就别在这里折腾了，沟通都不方便
