### ISSUE TITLE
When will the Big Sur EFI be published?

### ISSUE THREAD

**Issue by Iphone5-RecoveryMode** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#143]

**Comment by LoneFennecFoxy** [comment]
I've been checking back on this repo all day waiting for it, and I'm not sure. The developer may be in a different time zone which means they may have not been up when Apple released Big Sur.

**Comment by XayahSuSuSu** [comment]
Looking forward too

**Comment by RayneScofield** [comment]
be patient, sit tight.
