### ISSUE TITLE
Issues with hackintoshing Legion Y530

### ISSUE THREAD

**Issue by LoneFennecFoxy** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#145]
So starting off, I started with OpenCore. OpenCore boots to the first screen of installation, but touchpad doesn't work and I can't get Itlwm(OpenIntel) kext or the other variant working.

Now I've tried Clover as I've had success with them before, I absolutly love the UI of the bool menu on clover @xiaoMGitHub it's sad to see OC so plain and bare. But the issues I have with trying to boot clover is I get stuck at EXITBS:START.

Could you help me resolve these issues and explain the issue to me?

**Comment by hmthang96** [comment]
The touchpad would work after you finished the installer and ran the scrip.

OpenIntel: put your kext on kext folder and snapshot OC again.

**Comment by xiaoMGitHub** [comment]
Chinese New Year will be updated
