### ISSUE TITLE
Touchpad, Audio, Sleep Not Working on Big Sur

### ISSUE THREAD

**Issue by indowebdeveloper** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#149]
Hello, i'm successfull to install big sur ( official release ) but the Touchpad, Audio and Sleep didnt work

My laptop is Lenovo Y540

i did try the optimization script but it didnt work ( it gives me error code 37 on terminal when execute it )

any clue how to make it work on Big Sur ?

**Comment by Sevii69** [comment]
Hello, did you use the EFI from here? Or did you made you'r own? If yes, can you share it? Thanks

**Comment by Iphone5-RecoveryMode** [comment]
yeah I got Big Sur working by just updating opencore and making a new efi based on the one here. Audio injection failed so you'd need an ssdt-brg0 made for that (I don't know how to do that).

**Comment by MiSalocin** [comment]
I did get my audio working excluding ComandCenter in the files and the Config.plis, also, I've added "alcid=11" on NVRAM/Add/7C436110-AB2A-4BBB-A880-FE41995C9F82/boot-args and updated the UEFI>Audio configs on OpenCore configurator, changing the AudioDevice, AudioCodec and AudioSupport

**Comment by indowebdeveloper** [comment]
you may visit my repo https://github.com/indowebdeveloper/LegionY545_BigSur

> Hello, did you use the EFI from here? Or did you made you'r own? If yes, can you share it? Thanks
