### ISSUE TITLE
3.0.3 big sur?

### ISSUE THREAD

**Issue by zajavzek** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#150]
Download link to 3.0.3 support big sur? Any group not working. A lot of proples get 3.0.3 but everythink links dead

**Comment by hewad23** [comment]
whats your system?

**Comment by zajavzek** [comment]
10.15 on efi 3.0.2 but i want to 11.0.1 on efi 3.0.3

**Comment by LoneFennecFoxy** [comment]
I want efi 3.0.3 so I could get on bigsur too.

**Comment by zajavzek** [comment]
Bro i ask about 3.0.3efi

**Comment by Nurlan199206** [comment]
seems @xiaoMGitHub tired from Hackintosh :)

**Comment by LoneFennecFoxy** [comment]
> 
> 
> seems @xiaoMGitHub tired from Hackintosh :)

Well he was active recently within the month. Hope everything is okay with @xiaoMGitHub
