### ISSUE TITLE
作者已经不再在Github更新此库了（no longer update it in GitHub）

### ISSUE THREAD

**Issue by XayahSuSuSu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#152]
作者说了，加群才能获得最新的efi并且不再在GitHub更新
The author said that only by adding QQ groups can we get the latest EFI and no longer update it in GitHub

**Comment by xiaoMGitHub** [comment]
后续有时间会继续更新，感谢对y7000系列EFI的一直支持

**Comment by LoneFennecFoxy** [comment]
> 
> 
> 作者说了，加群才能获得最新的efi并且不再在GitHub更新
> The author said that only by adding QQ groups can we get the latest EFI and no longer update it in GitHub



> 
> 
> 后续有时间会继续更新，感谢对y7000系列EFI的一直支持

There's just 1 issue with the QQ group, users like myself in the United States are unable to access QQ. This means we're unable to obtain the EFI since we cannot join the QQ group. Is there any alternatives for users like myself? Thank you for your great work.

**Comment by Iphone5-RecoveryMode** [comment]
QQ is a straight up pain in the arse to get registered.

**Comment by pinkpeachabc** [comment]
> > 作者说了，加群才能获得最新的efi并且不再在GitHub更新
> > The author said that only by adding QQ groups can we get the latest EFI and no longer update it in GitHub
> 
> > 后续有时间会继续更新，感谢对y7000系列EFI的一直支持
> 
> There's just 1 issue with the QQ group, users like myself in the United States are unable to access QQ. This means we're unable to obtain the EFI since we cannot join the QQ group. Is there any alternatives for users like myself? Thank you for your great work.

You can leave an email and I'll send you the latest EFI
