### ISSUE TITLE
BigSur EFI folder.

### ISSUE THREAD

**Issue by Sevii69** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#153]
Hello! Can someone share a group or a link for the latest EFI folder? Because I can't find it anywhere. Also I can't join QQ because I don't know Chinese ...
Thank you in advance :) 💯

**Comment by doswo** [comment]
just message me , moogila@outlook.com

**Comment by doswo** [comment]
the QQ group is paid,so  i think u  could not  join  it

**Comment by Sevii69** [comment]
I've sent you a message

**Comment by LoneFennecFoxy** [comment]
I too sent a message.

**Comment by ShibuInu** [comment]
can someone also send me the efi?
