### ISSUE TITLE
Big Sur EFI

### ISSUE THREAD

**Issue by Iphone5-RecoveryMode** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#154]
When is the efi going to be released?

**Comment by xiaoMGitHub** [comment]
EFI 3.0.3 will be updated during Chinese New Year.

**Comment by nikolaj08131970** [comment]
уважаемый xiaoMGitHub  поздравляю с праздником весны-новым годом ------здоровья  радости и богатства
