### ISSUE TITLE
Updated BIOS Version BHCN33WW Issue

### ISSUE THREAD

**Issue by Tomato666665** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#156]
I am using Legion Y7000P 2019 PG0, after clicked Windows Upated, it upgraded the BIOS version to BHCN33WW (2020-Oct Release as Ciritical)
Then the 3.02 version using Clover is hang after click the "boot" screen.
I tried to load less Patched AML files and change the BIOS settion "Discrete Display Card", which is a new option for this updated BIOS.
Finally, I could login Mac OS, but the mouse pad, power management and the hardware acceleration of the "Intel(R) UHD Graphics 630" could not be used.
So the screen is quite lagging and could not open the Final Cut Pro, which pop error message "Could not open due to the hardware accelearion could not be used".

Is it any possible solution to solve it?

**Comment by xiaoMGitHub** [comment]
Do not set Discrete Display Card in BIOS.

**Comment by Tomato666665** [comment]
Thanks for the quick response.
Actually, I set the "Graphic Device" value as " Switchable Graphics" 
But when login in the MacOS, it is already use the "screen lagging" and when open "Final Cut Pro", it popup "graphics configuration not supported". I do think the "Intet UHD Graphics 630" hardware acceleration is disabled after the combination of BIOS upgrade and the Clover configuration.
