### ISSUE TITLE
[QUESTION] Wireless network card

### ISSUE THREAD

**Issue by LoneFennecFoxy** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#157]
What wireless network card would be best for the Lenovo Legion Y530?

**Comment by xiaoMGitHub** [comment]
BCM94352z （DW1560）
BCM94360NG
BCM94360CS2
BCM943602CS
BCM943602BAED （DW1830）
BCM94360CD
BCM94360Z4 （new card）

**Comment by LoneFennecFoxy** [comment]
> BCM94352z （DW1560）
> 
> BCM94360NG
> 
> BCM94360CS2
> 
> BCM943602CS
> 
> BCM943602BAED （DW1830）
> 
> BCM94360CD
> 
> BCM94360Z4 （new card）

Which do you recommend? (Having best connectivity, speeds, and all round compatibility?)

**Comment by LoneFennecFoxy** [comment]
@xiaoMGitHub I saw that you use the bcm943602cs, and that you're using an adapter. If that's still true today, how are you securing the card down with that adapter?

**Comment by xiaoMGitHub** [comment]
![image](https://user-images.githubusercontent.com/23020844/106109001-fee59180-6183-11eb-8c1c-7c17420edceb.png)
Use a riser card

**Comment by LoneFennecFoxy** [comment]
@xiaoMGitHub How did you secure it though, there's no spot for you to screw in the network card itself.

**Comment by xiaoMGitHub** [comment]
The original network card position is enough to put down the 2cs and the adapter card. At present, I have replaced a better BCM94360CD.
