### ISSUE TITLE
从windows热重启进入Mac后丢失声卡驱动

### ISSUE THREAD

**Issue by CityThameslink** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#158]
系统是10.15.4 19E266 目前发现的Bug是从windows热重启到Mac系统时会掉声卡驱动 触控板驱动有时也会掉 唯一的解决办法是关机再启动 请问是否有更好的解决办法

**Comment by xiaoMGitHub** [comment]
如果是机械盘，建议更换固态，同时更新引导驱动这些到最新版本

**Comment by tenetenet** [comment]
硬盘是三星的860evo 应该不是硬件问题 请问如何更新引导驱动

**Comment by xiaoMGitHub** [comment]
[acidanthera](https://github.com/acidanthera/)
