### ISSUE TITLE
Stucks at End RandomSeed

### ISSUE THREAD

**Issue by LuckyCrack** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#160]
![IMG_20210125_145145](https://user-images.githubusercontent.com/52278666/105690386-eece7780-5f21-11eb-87d8-f2adbf610b17.jpg)

## Cant Reach the installer screen

**Comment by xiaoMGitHub** [comment]
Try to replace OC

**Comment by LuckyCrack** [comment]
## Tried OC 

![IMG_20210125_180407](https://user-images.githubusercontent.com/52278666/105805632-6bb42c80-5fc8-11eb-908e-49cd66db86e5.jpg)

Also, i tried to remove this kext from config.plist but still no success.

**Comment by xiaoMGitHub** [comment]
Maybe there is a problem with your OC EFI.

**Comment by LuckyCrack** [comment]
I placed your provided Efi in the efi partition. Thats how we are supposed to do it right?

**Comment by LuckyCrack** [comment]
> 
> 
> Maybe there is a problem with your OC EFI.

How do i fix it?
