### ISSUE TITLE
OC引导10.15.6，每次出完Legion的logo后都会提示Failed to parse string field of type 2

### ISSUE THREAD

**Issue by CityThameslink** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#161]
EFI 3.0.2, 已升级AppleALC，Lilu， VirtualSMC， NVMeFix，WhateverGreen，AirportBrcmFixup 等驱动到最新版，可正常进入系统，但每次开机都有这段话（更新kext前，首次引导就有了）。网上有说是因为OpenCore Configurator生成的系统信息会自动生成Datahub, PlatfromNVRAM, SMBIOS，需要用xcode删除这三个文件。用这个方法后直接卡在一个禁止符号的介面，最终替换原始EFI后才重新进入了系统。也有人指出是OC版本和OCC不对应所致，但我OCC版本是1.21，完全支持0.5.7。想请问一下是什么可能导致了该错误，有没有对应的解决办法？
另外请问一下EFI3.0.2是否支持AudioDxe.efi以实现开机声音？我按照一些教程在OCC上添加过，但没有成功，提示无法加载。
不好意思问题有点多，实在麻烦了

**Comment by xiaoMGitHub** [comment]
OpenCore Configurator 需要用对版本，印象中3.0.2的OC版本应该是0.5.7。AudioDxe.efi在OC下面是支持的，居然0.5.7支不支持自行测试，目前没有计划在github上传新版OC EFI 的打算。
