### ISSUE TITLE
3.03

### ISSUE THREAD

**Issue by michael-no-1** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#163]
3.03春节发布吗

**Comment by xiaoMGitHub** [comment]
不确定，目前的EFI也貌似啥问题，自行升级下引导版本即可

**Comment by michael-no-1** [comment]
> 不确定，目前的EFI也貌似啥问题，自行升级下引导版本即可

我升级了，但是进不了，bigsur，但是能进10.15.7，可是引导过程没有进度条！这是大问题不，用不用退回去之前的引导？

**Comment by nikolaj08131970** [comment]
уважаемый xiaoMGitHub ! к очень большому сожалению имею не работающий bluetooth for Catalina и big sur 
процеcсор i7 9750
