### ISSUE TITLE
EFI for macOS Big Sur

### ISSUE THREAD

**Issue by HuaAnhMinh** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#165]
Is there anyone have the EFI config for macOS Big Sur. I'm using the release in this repo but it's not working.

**Comment by xiaoMGitHub** [comment]
Not surprisingly, it will be updated during the Chinese New Year.

**Comment by Nurlan199206** [comment]
@xiaoMGitHub you will release 3.0.3 clover version?

**Comment by xiaoMGitHub** [comment]
> @xiaoMGitHub you will release 3.0.3 clover version?

Unfortunately, clover performed poorly on bigsur, and there is no plan to update the clover version.

**Comment by Nurlan199206** [comment]
i can replace Clover to OC without reinstalling etc..?

**Comment by xiaoMGitHub** [comment]
Under normal circumstances, just replace it directly.
