### ISSUE TITLE
No recovery image on boot menu

### ISSUE THREAD

**Issue by LoneFennecFoxy** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#166]
I've booted to opencore using the new EFI and I've followed the new opencore guide to getting the recovery image. I can't get opencore to give me the boot option for recovery.![image](https://user-images.githubusercontent.com/74285788/107728498-dd23f880-6cb3-11eb-8b9a-5dfad46d97eb.jpeg)![image](https://user-images.githubusercontent.com/74285788/107728512-e57c3380-6cb3-11eb-82a8-6bfc80edab56.jpeg)![image](https://user-images.githubusercontent.com/74285788/107728516-ea40e780-6cb3-11eb-9348-241126d6b397.jpeg)

**Comment by xiaoMGitHub** [comment]
Try to press space in the system selection interface.

**Comment by LoneFennecFoxy** [comment]
> Try to press space in the system selection interface.

Thank you, this has given me the EFI option. Now I'm stuck at exitbs: start. But I've had this issue before, so I'll try to fox it on my own. I'll write down what I do to fix this issue so you can check it out.

My system is the Legion Y530 with the 8th gen i7

**Comment by LoneFennecFoxy** [comment]
How I got past the exitbs issue was to change AppleXcpmCfgLock from false to true.

https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#intel-users

**Comment by LoneFennecFoxy** [comment]
@xiaoMGitHub I'm now getting stuck at here which I've had no progression. I cannot find anything regarding the issue. ![image](https://user-images.githubusercontent.com/74285788/107779150-96152200-6d0a-11eb-9f11-d075b184002f.jpeg)

**Comment by xiaoMGitHub** [comment]
It is recommended to read the EFI instructions carefully first, of course you may need Google translation.

**Comment by LoneFennecFoxy** [comment]
> It is recommended to read the EFI instructions carefully first, of course you may need Google translation.

@xiaoMGitHub The only thing here I'm seeing that I'm not doing is the one-click bios tool. Personally I'm uncomfortable flashing bios due to fear of bricking my system. And my system has access to advanced bios. Other than that the readme doesn't have anything more to say. After the bios tool it says to replace EFI which I've done and booting doesn't work.

**Comment by LoneFennecFoxy** [comment]
Fixed it by changing vram in bios from 32mb to 64mb. Thank you for the release of EFI 3.0.6. Great work!
