### ISSUE TITLE
PANIC KERNEL BOOT WITH USB

### ISSUE THREAD

**Issue by bouhka** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#170]
HI, MY DEVICE IS LEGION 5I 10750H 144Z.TEST YOUR EFI 3.0.3 AND WITH USB INSTALLER I GET THIS:
panic(cpu 0 caller 0xffffff7fb7d38b5f): assertmsg@/Library/Caches/com.apple.xbs/Sources/GPUDriversIntel/GPUDriversIntel-16.0.49/IONDRV/CFL/AppleIntelFramebuffer/AppleIntelController.cpp:29327

I AM CURRENTLY USING BIG SUR WITH EFI DE OLARILA (CREDITS TONFORIA, MALDON AND LAUI).
EVERYTHING IS GOING WELL EXCEPT TRACKPAD, BUT THIS IS NOT MY BIGGEST CONCERN. THE ONLY DRAWING IS THE HIGH 50W MINIMUM POWER CONSUMPTION. I WANTED TO TEST YOUR EFI TO KNOW IF YOU CAN REDUCE CONSUMPTION THANKS. (DID YOU GET TO TURN OFF NVIDIA ON YOUR EFI?)

**Comment by LuckyCrack** [comment]
Hey i had same issue Here's how i fixed it 

Under "DeviceProperties" make "PciRoot(0x0)/Pci(0x2,0x0)" look like this
![deviceproperties](https://user-images.githubusercontent.com/52278666/107871246-cd7bfe00-6ec5-11eb-804e-ece4590e0d2e.PNG)

And add this Boot-arg "-igfxmlr"

**Comment by xiaoMGitHub** [comment]
To use my EFI, it is recommended to read the EFI instructions carefully. My EFI needs to be used with another tool.
