### ISSUE TITLE
Brightness control

### ISSUE THREAD

**Issue by rlfto** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#171]
Hi,

Thank you for your great work on this EFI

I successfully installed Big Sur on my Legion 5i. With a bit modifications, everything works except the screen brightness. 

The brightness slider is present on display settings but there is not any change in the screen. The solutions I tried until now:
1./ SSDT-PNLFCFL + Lilu + Whatevergreen 
2./ SSDT-PNLF + Lilu + Whatevergreen 
3./ SSDT-PNLFCFL + RehabMan brightness fixup
4./ SSDT-PNLF + RehabMan brightness fixup
5./ All the combinations above + SSDT-ALS0 + SMCLightSensor.kext (for adding fake ambient sensor). In this case, moving the slider changes just a little bit (almost imperceptible) the brightness level on the screen.

Do you have any recommendation to fix this issue?

Best regards.

**Comment by xiaoMGitHub** [comment]
After testing , it can be solved by replacing the screen.
