### ISSUE TITLE
OC: Failed to load configuration

### ISSUE THREAD

**Issue by shehab910** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#172]
It displays that error when I boot from my USB (BigSur), I don't know what exactly is the issue I followed the readme instructions (bios settings and LEGION_Y7000Series_Insyde_Advanced_Settings_Tools) and placed the EFI folder in the EFI partition.
Thanks for your efforts.

EFI used from release 3.0.3

My laptop model: y540
intel i7 9750h

**Comment by Gyq0101** [comment]
> It displays that error when I boot from my USB (BigSur), I don't know what exactly is the issue I followed the readme instructions (bios settings and LEGION_Y7000Series_Insyde_Advanced_Settings_Tools) and placed the EFI folder in the EFI partition.
> Thanks for your efforts.
> 
> EFI used from release 3.0.3
> 
> My laptop model: y540
> intel i7 9750h

rename

**Comment by SydneyCat** [comment]
> rename

you should choose one .plist file that matches your requirement and rename it as config.plist.
the  .plist file is in /efi/oc

**Comment by shehab910** [comment]
> > rename
> 
> you should choose one .plist file that matches your requirement and rename it as config.plist.
> the .plist file is in /efi/oc

thank you so much that was the problem and thanks to @xiaoMGitHub I have macOS big sur up and running on my y540 flawlessly.
