### ISSUE TITLE
8m显存解决方案

### ISSUE THREAD

**Issue by michael-no-1** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#174]

**Comment by michael-no-1** [comment]
![Uploading B5C2CB36B2D62F7013EA82253EA770EF.jpg…]()

**Comment by michael-no-1** [comment]
![B5C2CB36B2D62F7013EA82253EA770EF](https://user-images.githubusercontent.com/77877849/108148994-e9bdac00-710c-11eb-965f-5e9bb8a2f487.jpg)

**Comment by xiaoMGitHub** [comment]
操作问题
