### ISSUE TITLE
Booting issue in Legiony540(9300H)

### ISSUE THREAD

**Issue by GautamMakadia** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#175]
I have legion Y540(9300H),

I use usb installer, i am able to boot into opencore but when i select the "installer" it reboots after mid of processbar.

i can't able to boot into MacOS recovery(Big Sur).

stuck at : Generation from SMC report as 2
![PXL_20210219_174622127](https://user-images.githubusercontent.com/69979317/108542631-feb35e80-7309-11eb-92f4-ec4b84d45f86.jpg)

**Comment by cogiaphuc97** [comment]
hi @GautamMakadia i've solve the problem by running the [https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/tree/master/BIOS_Setup](BIOS tool )

**Comment by xiaoMGitHub** [comment]
First, you need to follow the EFI operating instructions.
