### ISSUE TITLE
SSDT GPU

### ISSUE THREAD

**Issue by liteon6x** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#177]
Hello can you patch my SSDT and make a 
SSDT DDGPU file for me please
the one you provided makes my GPU fan run at max speed and loud fans 

[origin.zip](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/files/6044887/origin.zip)

**Comment by xiaoMGitHub** [comment]
The current 10XXXH version of legion cannot block the discrete graphics card through SSDT

**Comment by liteon6x** [comment]
Is the problem only with the 10th gen Lenovo

Or do all 10th gen chips have the problems FROM ALL vendors?

**Comment by xiaoMGitHub** [comment]
It should just be Lenovo's problem.

**Comment by bouhka** [comment]
HI HAVE YOU TRIED ALL POSSIBLE METHODS TO BLOCK DGPU?  OR HAVE JUST TESTED SSDT? THANK YOU

**Comment by xiaoMGitHub** [comment]
> HI HAVE YOU TRIED ALL POSSIBLE METHODS TO BLOCK DGPU? OR HAVE JUST TESTED SSDT? THANK YOU

Tried all possible methods. Of course, my ability alone is limited, or you have different ideas, if you solve it, please tell me in time, thank you.
