### ISSUE TITLE
continuation dGPU OFF

### ISSUE THREAD

**Issue by bouhka** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#178]
Hi  xiaoMGitHub , you know much more than me, i'm just beginning to know something.I was researching something in asus, it seems the optimus ssdt-ddgpu method doesn't work either. As I have seen in some efi, they are using the minimum energy method of dortania or variations of it.
Here they confirmed that the battery works from 5 to 8 hours, it seems a symptom of dDGPU OFF.
https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore/issues/6

https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore.
https://www.tmstweaks.com/post/2020/asus-zephyrus-m15-hackintosh/

**Comment by dkoluris** [comment]
Just to point you to the right direction, you will need to look into PTSWAK SSDT. For me this is key to keep dGPU off after waking up from sleep. Make sure that the temps on your CPU usage fall into the 30 to 35 degrees celsius category.

**Comment by bouhka** [comment]
To eliminate doubts, did the problem of consumption and temperature (55-60) only have it when waking up, or was it at any time, even when starting Mac OS? This would be important because it would confirm that the problem of turning off the dGPU is from Lenovo and not from Asus.

**Comment by dkoluris** [comment]
For me the problem was only when waking up from sleep. Then I researched to add PTSWAK and some config.plist patches, and the problem was solved.

**Comment by love796-QAQ** [comment]
> 为了消除疑问，消耗和温度问题（55-60）只是在唤醒时才出现，还是在任何时候甚至在启动Mac OS时都出现了？这很重要，因为它可以确认关闭dGPU的问题是由Lenovo而非华硕造成的。

Have you found a solution? I have the same problem as you.

**Comment by bouhka** [comment]
> > 为了消除疑问，消耗和温度问题（55-60）只是在唤醒时才出现，还是在任何时候甚至在启动Mac OS时都出现了？这很重要，因为它可以确认关闭dGPU的问题是由Lenovo而非华硕造成的。
> 
> Have you found a solution? I have the same problem as you.
DO YOU HAVE LENOVO OR ASUS?

**Comment by love796-QAQ** [comment]
> > > 为了消除疑问，消耗和温度问题（55-60）只是在唤醒时才出现，还是在任何时候甚至在启动Mac OS时都出现了？这很重要，因为它可以确认关闭dGPU的问题是由Lenovo而非华硕造成的。
> > 
> > 
> > Have you found a solution? I have the same problem as you.
> > DO YOU HAVE LENOVO OR ASUS?

I have Lenovo

**Comment by bouhka** [comment]
> > > > 为了消除疑问，消耗和温度问题（55-60）只是在唤醒时才出现，还是在任何时候甚至在启动Mac OS时都出现了？这很重要，因为它可以确认关闭dGPU的问题是由Lenovo而非华硕造成的。
> > > 
> > > 
> > > Have you found a solution? I have the same problem as you.
> > > DO YOU HAVE LENOVO OR ASUS?
> 
> I have Lenovo
I do not have the solution unfortunately. Just investigate if you are only a Lenovo problem, and for what you read in this thread for now we know that if. We will have to wait for those who know the most of this contribution, meanwhile I will continue looking for the solution.

**Comment by xiaoMGitHub** [comment]
At present, it should be certain that Lenovo’s problem is, of course, it may also be caused by our lack of cognition.

**Comment by bouhka** [comment]
> At present, it should be certain that Lenovo’s problem is, of course, it may also be caused by our lack of cognition.

I am still not very clear that it is only a lenovo problem.  In this link use the minimum energy method.  I asked the user, I am still waiting for him to answer.
https://www.tmstweaks.com/post/2020/asus-zephyrus-m15-hackintosh/

**Comment by bouhka** [comment]
Hi xiaoMGitHub .In your previous legion y540 project, how did you know that the dGPU is off?  -Thank you

**Comment by xiaoMGitHub** [comment]
In the BIOS, set Configuration> DPTF to Disabled, so that you can use hotpatch to disable the DGPU.

**Comment by xiaoMGitHub** [comment]
> Hi xiaoMGitHub .In your previous legion y540 project, how did you know that the dGPU is off? -Thank you

In the BIOS, set Configuration> DPTF to Disabled, so that you can use hotpatch to disable the DGPU.

**Comment by bouhka** [comment]
Hi xiaoMgithub .Uninstall bigSur, for this problem. Your EFi February 11 is compatible for Monterrey final. You could give support by Paypal if you have the efi working for Monterrey. Thank you
