### ISSUE TITLE
Y540 - Intel UHD 7MB

### ISSUE THREAD

**Issue by omriileviii** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#180]
Hi I just install Big Sur Intel UHD With Config attach to post and with EFI: https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh
please help me to fix Intel UHD 7 MB

config: [Config.plist](https://www.tonymacx86.com/attachments/config-plist.512174/)

**Comment by xiaoMGitHub** [comment]
Switch graphics mode

**Comment by omriileviii** [comment]
I was
