### ISSUE TITLE
SSD INSTALLATION ISSUE

### ISSUE THREAD

**Issue by GautamMakadia** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#182]
I have samsung pre-installed SSD that came when I purchased laptop, 

I have successfully installed macos bigsur on hdd.
Now I have to install on SSD, but the installer reboots after reaching at 14min remaining.

SSD : samsung MZVLB25HBHQ-00L2 having 
Already windows installed and 118gb free partition to install macos
![IMG_20210327_122423515](https://user-images.githubusercontent.com/69979317/112712779-740ce300-8ef7-11eb-9ff8-ab853e6a3fba.jpg)

**Comment by xiaoMGitHub** [comment]
I’m sorry to tell you that the models starting with MZLVB hesitate about compatibility issues and cannot install MacOS.

**Comment by GautamMakadia** [comment]
Is there any way to fix this?
