### ISSUE TITLE
 在10.13.6  high sierra中可以驱动独显1050 ti 吗？？

### ISSUE THREAD

**Issue by RyanGf** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#183]
大神，我想在10.13.6  high sierra中驱动独显1050 ti，可以实现吗？我已经安装了对应的 nvidia web driver，并在配置文件设置了相关配置，但无效。能告诉我应该怎么做吗？？

**Comment by xiaoMGitHub** [comment]
不可以，可能原因是被阉割了必要的硬件
