### ISSUE TITLE
Cannot boot Big Sur Installer Legion Y540

### ISSUE THREAD

**Issue by SaravananSudesh** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#185]
Catalina worked but Big Sur isn’t working on my Legion Y540
-My Specs-
i7-9760H
32 GB Ram
Intel UHD 630 (Nvidia GTX 1650 disabled)
1TB WD M.2
![image](https://user-images.githubusercontent.com/50314017/114691477-5af89480-9d35-11eb-80a7-45d8ee63e31f.jpg)
![image](https://user-images.githubusercontent.com/50314017/114691557-6d72ce00-9d35-11eb-8b68-8e1c8789308c.jpg)

**Comment by xiaoMGitHub** [comment]
Execute the modified BIOS [script](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools).

**Comment by HarryHeres** [comment]
@SaravananSudesh Look at my closed issue, there is a complete guide on how I have managed to overcome this issue..
