### ISSUE TITLE
The trackpad is not working on freshly installed Big Sur 11.3

### ISSUE THREAD

**Issue by md-siam** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#186]
![twitter_p5u-UQu0](https://user-images.githubusercontent.com/21225918/116168678-d0486a00-a724-11eb-85ff-8270d2a5d1ec.jpg)

**Comment by GautamMakadia** [comment]
I have this issue also

**Comment by GautamMakadia** [comment]
just reboot the system and it will be fixed, 

I also have this issue after updating to BigSur 11.3.

**Comment by HarryHeres** [comment]
I've got the same problem, restarting did not help :/ When I looked into the booting process, the ApplePS2Controller.kext didn't recognize my trackpad.

**Comment by GautamMakadia** [comment]
> I've got the same problem, restarting did not help :/ When I looked into the booting process, the ApplePS2Controller.kext didn't recognize my trackpad.

Have you get trackpad working?

**Comment by hmthang96** [comment]
go to advanced bios and change touchpad to serial 0 to work

**Comment by GautamMakadia** [comment]
> go to advanced bios and change touchpad to serial 0 to work

Do you know how to enable advanced bios?
Tell me.

**Comment by hmthang96** [comment]
https://github.com/xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools
You can use this tool to fix without goto advanced bios
