### ISSUE TITLE
how to use external monitor for y540

### ISSUE THREAD

**Issue by ducuong2018** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#194]
i am having problem not receiving external monitor on y540 big sur, i tried plugging in mini display to hdmi, usb-c to displayport, it doesn't work, can you help me to make it work?

**Comment by hoacongankg** [comment]
900k mua usb díplaylink đi bạn, cổng HDMI, mini Dp nó để nối qua card rời, mà card rời bị tắt rồi. Nên ko xuất hình ảnh được đâu

**Comment by ducuong2018** [comment]
> 900k mua usb díplaylink đi bạn, cổng HDMI, mini Dp nó để nối qua card rời, mà card rời bị tắt rồi. Nên ko xuất hình ảnh được đâu

bác ơi, bác có đang dùng nó không ? tại mình đang ở quê ý, mà đặt về không dùng được thì phí, và liệu usb-c có dùng được không bác, hay chỉ mỗi usb

**Comment by hoacongankg** [comment]
Mình đang dùng mỗi ngày. Giá tầm khoảng 900k. Tên là Unitek y-3702. Xuất qua cổng Usb A. Còn usb type-C trên con y540 nó cũng đc nối với card rời nên không xuất hình từ igpu qua đó đc bạn nhé

**Comment by ducuong2018** [comment]
Vâng, thế mình cảm ơn bác nhiều, để mình đặt về dùng thử xem !
