### ISSUE TITLE
4K显示器问题

### ISSUE THREAD

**Issue by CallMe-star** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#197]
大佬，我电脑型号Y7000P 2020款的，想接一个4K显示器，DP转接到电脑的usb插口，但是他那转接线没有外置显卡，可不可以通过改哪个config文件，达到适配4K显示器的效果啊。还是说必须得买一个支持4k的HDMI转USB的转接头才行呢

**Comment by xiaoMGitHub** [comment]
有钱就换电脑，没钱就买个USB转接头

**Comment by CallMe-star** [comment]
大佬，谢谢解惑。我是想问那种HDMI母口转成usb插在电脑上的转接线这种可以吗。（是只要是通过usb接电脑就行，还是必须有外置显卡的转换头才行啊）或者大佬给推荐个支持4K的转接头呗

**Comment by xiaoMGitHub** [comment]
挑贵的买，几十块钱的别碰，两三百起步
