### ISSUE TITLE
Monterey Beta install boot looping OC 0.6.6

### ISSUE THREAD

**Issue by Gracham** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#198]
Hey!
I installed latest Big Sur Beta without any problems but it can't install Monterey Beta. After initial instal within Big Sur and booting into "Mackintosh HD" the progress bar will move a bit and then restart the laptop. I tried putting -lilubetaall and updating kexts but it did not work. I got a photo of verbose and seems like kernel is panicking. 
Would be thankful for any tips or advice
Thank you for your hard work! 
![2021-07-08 12 50 07](https://user-images.githubusercontent.com/47783439/124909721-15bdc900-dfeb-11eb-854e-9349c7372e9d.jpg)

y530-1060
i7-8750h
1060
Stock network card
Crucial P2 NVMe 
OC 0.6.6

**Comment by xiaoMGitHub** [comment]
Try to remove CpuTscSync.kext or add cups=1 boot-args

**Comment by Gracham** [comment]
> Try to remove CpuTscSync.kext or add cups=1 boot-args

Removing CpuTscSync from EFI/OC/Kexts - doesn't boot to big sur or install
![2021-07-09 10 05 20](https://user-images.githubusercontent.com/47783439/125045461-4f4f0c80-e09d-11eb-8080-d2014131b22e.jpg)

Adding cpus=1 boot-args - boots to big sur, panick on Monterey install
![2021-07-09 10 06 22](https://user-images.githubusercontent.com/47783439/125045569-6d1c7180-e09d-11eb-83ba-a85317c02311.jpg)

**Comment by xiaoMGitHub** [comment]
Should be cpus=1

**Comment by Gracham** [comment]
Sorry, my mistake. cpus=1 got the verbose further but still reboots and doesnt install. I recorded the verbose here

Something with SMC
https://user-images.githubusercontent.com/47783439/125095730-c6ec5e00-e0d4-11eb-99d1-cd48312b6355.mp4

https://youtu.be/rVpS3ACMoaU

**Comment by xiaoMGitHub** [comment]
Change Misc-Security-SecureBootModel to Disabled

**Comment by Gracham** [comment]
> Change Misc-Security-SecureBootModel to Disabled

Already changed that after some googling. Still no difference. Gave up on the Hackintosh for a awhile because i couldn't get BCM94352z to work. Thans for your help and work
