### ISSUE TITLE
Y7000 2018版 声音输出耳机问题

### ISSUE THREAD

**Issue by lightyisu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#200]
使用OC引导Big sur11.1 20C69 使用时默认的耳机输出声音很奇怪 几乎听不清声音
调整平衡至左右后可以听清但确实也不太平衡了，请问dalao这个是什么原因呢 
之前在上一个mac大版本也用过 当时没想到换平衡 用的CLOVER的引导 加了个VoodooHDA.kext就能使用
但我的电脑修过也许可能是修过的原因 还请dalao有什么思路和解答，谢谢
![QQ图片20210801140500](https://user-images.githubusercontent.com/45456944/127773764-93df6889-db06-45d9-9a0c-ce559f78f21e.jpg)

**Comment by lightyisu** [comment]
扬声器正常

**Comment by xrervip** [comment]
这次通过下面的方法解决的黑苹果声音低、有杂音、爆音的问题
| 参数 |内容  |
|--|--|
|机型  |联想Y7000 2018  |
| OS| 卡特琳娜 10.15.3 |
|EFI与引导|Clover 来自[https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh)|

按照原EFI中采用的声卡是AppleALC.kext
这里参考了CSDN[黑苹果声音低、有杂音、爆音解决方案](https://blog.csdn.net/xiaobo060/article/details/105054633)，但是没有解决问题

## 0.如果需要的话重装AppleALC.kext
使用Clover挂载EFI分区，打开分区，驱动路径：/EFI/CLOVER/kexts/Other/ 删除路径下的AppleALC.kext、Lilu.kext（AppleALC.kext所依赖的驱动）
然后重新下载，拖入文件导入驱动
AppleALC下载地址：
[https://github.com/acidanthera/AppleALC/releases](https://github.com/acidanthera/AppleALC/releases)

Lilu下载地址：
[https://github.com/acidanthera/Lilu/releases](https://github.com/acidanthera/Lilu/releases)


## 1.在win10或者PE下查看真实声卡型号
这里给出win10下查看的方法

喇叭点击右键-声音-播放器-扬声器-属性-控制器信息：属性-详细信息-下拉栏选择硬件ID-记住DEV_后面的几位数字
![在这里插入图片描述](https://img-blog.csdnimg.cn/2021052420481872.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
如图所示，y7000配置的瑞昱声卡的型号是（ACL）236

再上GitHub [Supported codecs](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)查找自己声卡对应的id
![在这里插入图片描述](https://img-blog.csdnimg.cn/20210524205202756.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
如图所示ALC236对应的是

```
0x100001, 0x100002, layout 3, 11, 12, 13, 14, 15, 16, 18, 54, 99
```
## 2.修改Clover的引导参数
首先挂载EFI分区，打开config.plist文件
右键，选择添加alcid-layout参数
	![在这里插入图片描述](https://img-blog.csdnimg.cn/20210524205623362.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
	
根据查询结果将layout数值替换为声卡对应layout数值：15
	
即为：
```
alcid=15
```

重新启动系统，检查是否能够正常驱动自己的声卡，如果不能启动的话尝试更换其他参数

**Comment by xiaoMGitHub** [comment]
楼上的做法已经破坏了我的EFI，站在我的角度是不建议的；我更倾向于
1、使用iPhone送的耳机（因为我只有iPhone送的耳机不考虑其他品牌适配）
2、优化命令执行 '1、修复插耳机杂音'
3、这样插入耳机的时候输入输出都能自动切换，且毫无杂音

**Comment by lightyisu** [comment]
> 楼上的做法已经破坏了我的EFI，站在我的角度是不建议的；我更倾向于
> 1、使用iPhone送的耳机（因为我只有iPhone送的耳机不考虑其他品牌适配）
> 2、优化命令执行 '1、修复插耳机杂音'
> 3、这样插入耳机的时候输入输出都能自动切换，且毫无杂音

非常感谢！明白

**Comment by lightyisu** [comment]
> 
> 这次通过下面的方法解决的黑苹果声音低、有杂音、爆音的问题
> | 参数 |内容  |
> |--|--|
> |机型  |联想Y7000 2018  |
> | OS| 卡特琳娜 10.15.3 |
> |EFI与引导|Clover 来自[https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh)|
> 
> 按照原EFI中采用的声卡是AppleALC.kext
> 这里参考了CSDN[黑苹果声音低、有杂音、爆音解决方案](https://blog.csdn.net/xiaobo060/article/details/105054633)，但是没有解决问题
> 
> ## 0.如果需要的话重装AppleALC.kext
> 使用Clover挂载EFI分区，打开分区，驱动路径：/EFI/CLOVER/kexts/Other/ 删除路径下的AppleALC.kext、Lilu.kext（AppleALC.kext所依赖的驱动）
> 然后重新下载，拖入文件导入驱动
> AppleALC下载地址：
> [https://github.com/acidanthera/AppleALC/releases](https://github.com/acidanthera/AppleALC/releases)
> 
> Lilu下载地址：
> [https://github.com/acidanthera/Lilu/releases](https://github.com/acidanthera/Lilu/releases)
> 
> 
> ## 1.在win10或者PE下查看真实声卡型号
> 这里给出win10下查看的方法
> 
> 喇叭点击右键-声音-播放器-扬声器-属性-控制器信息：属性-详细信息-下拉栏选择硬件ID-记住DEV_后面的几位数字
> ![在这里插入图片描述](https://img-blog.csdnimg.cn/2021052420481872.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
> 如图所示，y7000配置的瑞昱声卡的型号是（ACL）236
> 
> 再上GitHub [Supported codecs](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs)查找自己声卡对应的id
> ![在这里插入图片描述](https://img-blog.csdnimg.cn/20210524205202756.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
> 如图所示ALC236对应的是
> 
> ```
> 0x100001, 0x100002, layout 3, 11, 12, 13, 14, 15, 16, 18, 54, 99
> ```
> ## 2.修改Clover的引导参数
> 首先挂载EFI分区，打开config.plist文件
> 右键，选择添加alcid-layout参数
> 	![在这里插入图片描述](https://img-blog.csdnimg.cn/20210524205623362.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0ZyYW5rbGluc19GYW4=,size_16,color_FFFFFF,t_70)
> 	
> 根据查询结果将layout数值替换为声卡对应layout数值：15
> 	
> 即为：
> ```
> alcid=15
> ```
> 
> 重新启动系统，检查是否能够正常驱动自己的声卡，如果不能启动的话尝试更换其他参数

感谢机友了，也是解决方法，但还是挺复杂哈哈，谢谢！
