### ISSUE TITLE
cursor/pointer lagging macOS Big Sur

### ISSUE THREAD

**Issue by Nurlan199206** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#201]
i have lagging touchpad cursor, you know how to fix it?

**Comment by xiaoMGitHub** [comment]
Using this [tool](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Insyde_Advanced_Settings_Tools), perform option 2.

**Comment by Nurlan199206** [comment]
wow, thank you! even swipes now work. Helped a lot!
