### ISSUE TITLE
y7000 i5 8300H 无征兆卡死（冻结）

### ISSUE THREAD

**Issue by z605** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#202]
请问有没有遇到过 正常使用时（毫无征兆），突然卡死的情况（画面有时候是冻结，有时候是黑屏。鼠标、键盘全部失效，音乐也停止）
  。
看system log 没有发现有相关的日志    打开啰嗦模式，引导没发现有什么报错  。  

这种情况偶尔几天就会出现一次，必须要强制重启 。 重启后， 恢复正常 。 
系统版本 11.2.1  OC 0.6.2  
![image](https://user-images.githubusercontent.com/19978828/130641397-f1feb439-9c2d-4dc0-b705-6321977d1b92.png)

启动参数 keepsyms=1 rtcfx_exclude=80-FF brcmfx-country=#a vsmcgen=1 igfxfw=2 -igfxblr igfxrpsc=1  

![image](https://user-images.githubusercontent.com/19978828/130641609-3fa2d665-5e92-41af-906d-a68e37227a9a.png)

请问这种情况 有什么办法trouble shoot吗？

**Comment by xiaoMGitHub** [comment]
印象中我没有提供过OC 0.6.2的版本，更换我提供的版本再尝试
