### ISSUE TITLE
Legion 5i Monterey 12.10

### ISSUE THREAD

**Issue by satmac75** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#208]
I was able to install beta 12.9 and then update to 12.10 Macos on y7000 2020.

What doesn't work for me are the:
Bluetooth (turns off by itself)
Brightness and maybe others that I did not test.

Also, Macos still unable to see my SK Hynix 512GB NVMe on PCIe port 2. (the port under the capsLk key), Interesting enough, hackintool detects it.

I can share with you the files if you are interest. I wont post them in my github out of respect to your work. 
Thanks for all the work you did for the community
![Screen Shot 2021-10-16 at 8 06 36 PM](https://user-images.githubusercontent.com/77470718/137605064-45215ad6-a68e-40d1-94a6-2c4cd36a2c89.png)

**Comment by Naser4100** [comment]
Audio and brightness control does not work for me on Monterey. Y530 - i7 8750h
