### ISSUE TITLE
Help Wanted! Upgrade from catalina 10.15.7 to big sur 11.6

### ISSUE THREAD

**Issue by ndev1991** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#209]
Hello! I really appreciate your great work and thank you!
I was able to install Catalina 10.15.7 by using 3.0.2 (not the latest, because it doesn't work for me). 
Catalina works great for me. The issue was bluetooth seems turned on but not working. 

But the main problem I tried to upgrade to Big Sur 11.6 but it stuck after restart. It just shows the apple logo and nothing. No progress bar. 
So i tried the latest 3.0.3, it shows the apple log and some progress but stuck.

My PC:
Lenovo Legion 81q5 y7000p 2019.
Intel Core i-7 9750h

Please help me!
I'm stuck here

Additionally I tried -v and showing attempting to restart on 0.6.6

**Comment by HarryHeres** [comment]
Hi, I recommend looking into one of my closed issues (#183). There is a guide about how I treated problems during Big Sur installation.

**Comment by ndev1991** [comment]
> Hi, I recommend looking into one of my closed issues (#184). There is a guide about how I treated problems during Big Sur installation.

Thanks @HarryHeres Can you point the correct one?

**Comment by Naser4100** [comment]
You can try using clover at that time. After completing installation you can use open core back again
