### ISSUE TITLE
咨询: y7000p 2021相关

### ISSUE THREAD

**Issue by SeanYanxml** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#210]
Hi~ 咨询2个问题
* 最新版是因为i11 芯片问题无法支持苹果么?
* 更换网卡和蓝牙后. Windows系统是否还能正常工作?

**Comment by xiaoMGitHub** [comment]
1、11支持安装黑苹果，只是11的核显没有驱动
2、基本上所有的网卡在win系统下都能驱动
