### ISSUE TITLE
y530 bigsur installation reboot unexpectedly

### ISSUE THREAD

**Issue by Richardleonn** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#212]
Hi,
I attempted to install big sur on my y530, system reboots unexpectedly in about 12 minutes remaining. After restart, OpenCore goes into apple logo without showing menu and restarts again and again.
Can someone help me? I really need to fix this.

This is a log:
[opencore-2021-11-23-215703.txt](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/files/7597594/opencore-2021-11-23-215703.txt)

**Comment by xiaoMGitHub** [comment]
Check if your hard drive model is Samsung PM981

**Comment by Richardleonn** [comment]
No it is Toshiba. Although I'm installing on HDD.

**Comment by Richardleonn** [comment]
> Check if your hard drive model is Samsung PM981

No it is Toshiba. Although I'm installing on HDD.

**Comment by Richardleonn** [comment]
@xiaoMGitHub I got this worked.
In installation when I create jhfs+ partition for macos, it installes but not boot into OS.
Now I created APFS instead and every is ok and Big Sur booted successfully.
However, A couple of restarts happened before complete finishing installation.
