### ISSUE TITLE
 macOS Monterey Final support

### ISSUE THREAD

**Issue by kodidono** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#213]
the final version of the new operating system has been released 
I can't wait for the new bootloader release from the boss

**Comment by Nurlan199206** [comment]
@xiaoMGitHub you have tried direct update from Big Sur to Monterey?

**Comment by xiaoMGitHub** [comment]
> @xiaoMGitHub you have tried direct update from Big Sur to Monterey?

There is no problem at all, just upgrade the version of OC to the latest.

**Comment by kodidono** [comment]
> > @xiaoMGitHub вы пробовали прямое обновление с Биг Сур до Монтерея?
> 
> Никаких проблем нет, просто обновите версию OC до последней.



> > @xiaoMGitHub you have tried direct update from Big Sur to Monterey?
> 
> There is no problem at all, just upgrade the version of OC to the latest.

**Comment by kodidono** [comment]
> > @xiaoMGitHub you have tried direct update from Big Sur to Monterey?
> 
> There is no problem at all, just upgrade the version of OC to the latest.

I read this is not so easy to do, there you need to make changes to the config, and I'm afraid of something to break

**Comment by kodidono** [comment]
> > > @xiaoMGitHub you have tried direct update from Big Sur to Monterey?
> > 
> > 
> > There is no problem at all, just upgrade the version of OC to the latest.
> 
> I read this is not so easy to do, there you need to make changes to the config, and I'm afraid of something to break

I also spent almost all day trying to update opencore using guides from YouTube..
I didn’t succeed, all that happens is that I’m a little crazy about all these instructions ^_^
it would be very cool if you updated the new release for this new year, as a gift to all users who follow your work here.
if you have enough time for that.
thanks a lot

**Comment by xiaoMGitHub** [comment]
> > > > @xiaoMGitHub you have tried direct update from Big Sur to Monterey?
> > > 
> > > 
> > > There is no problem at all, just upgrade the version of OC to the latest.
> > 
> > 
> > I read this is not so easy to do, there you need to make changes to the config, and I'm afraid of something to break
> 
> I also spent almost all day trying to update opencore using guides from YouTube.. I didn’t succeed, all that happens is that I’m a little crazy about all these instructions ^_^ it would be very cool if you updated the new release for this new year, as a gift to all users who follow your work here. if you have enough time for that. thanks a lot

In fact, I have replaced the MacBook Pro M1 for a long time, and it is expected that the next EFI update will be the Chinese New Year.

**Comment by kodidono** [comment]
> > > > > @xiaoMGitHub you have tried direct update from Big Sur to Monterey?
> > > > 
> > > > 
> > > > There is no problem at all, just upgrade the version of OC to the latest.
> > > 
> > > 
> > > I read this is not so easy to do, there you need to make changes to the config, and I'm afraid of something to break
> > 
> > 
> > I also spent almost all day trying to update opencore using guides from YouTube.. I didn’t succeed, all that happens is that I’m a little crazy about all these instructions ^_^ it would be very cool if you updated the new release for this new year, as a gift to all users who follow your work here. if you have enough time for that. thanks a lot
> 
> In fact, I have replaced the MacBook Pro M1 for a long time, and it is expected that the next EFI update will be the Chinese New Year.

thanks for the answer
