### ISSUE TITLE
Apple Logo stuck Open core 0.6.6

### ISSUE THREAD

**Issue by FC2714** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#217]
Hello. I have used the latest release from here. 0.6.6 and its EFI. USB boots normal, I choose Big sur installation. It loads normal for while until here .
![20211222_200456](https://user-images.githubusercontent.com/64442679/147122146-ceae8545-1307-4e2f-8a3d-2676202ee896.jpg)

Then suddenly this happens. 
![VideoCapture_20211222-200620](https://user-images.githubusercontent.com/64442679/147122193-5e5c6616-b962-4346-b377-e3ddbcfe5c65.jpg)

Then get backs to this stage and stucks here. 
![20211222_200458](https://user-images.githubusercontent.com/64442679/147122273-2449d15b-5fc4-4f28-ae4f-085a87398b8d.jpg)

My model is lenovo legion y530 2018. I was using in the past clover with olde release I guess 3.0.1 or 3.0.2. I wanted to do again with new release after while. But no success. 

I used this BIOS settings. 

Secure Boot : DisabledKernel Debug Serial Port : Legacy UART
Advanced -> Debug settings -> Legacy UARTCFG Lock (MSR_E2) : Disabled
Advanced -> Power & Performance -> CPU - Power Management -> View/Configure CPU Lock Options -> CFG LockDVMT Pre-Allocated Memory : 64MB
Advanced -> System Agent (SA) Configuration -> Graphics Configuration -> DVMT Pre-Allocated MemoryTrackpad GPIO: Enabled
Advanced -> PCH-IO config -> BIOS lock -> Security Config -> Enabled

**Comment by xiaoMGitHub** [comment]
Wait patiently, everything is normal

**Comment by FC2714** [comment]
> Wait patiently, everything is normal

How long should I wait? I wait for a while but bar does not even move a little
