### ISSUE TITLE
Sound, Brightness and Late opening

### ISSUE THREAD

**Issue by FC2714** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#218]
I was able to install mac os catalina with 0.6.6 EFI folder. Everything worked. Then I wanted to update to Monterey. I got issue that firmware coud not be installed. Found a fix fot that updated opencore to latest version with drivers. It fixed issue. I updated to monterey. But after update I have 3 issues.
1.Can not adjust Brightness
2. No sound output and input.
3. After booting the login screen appears after 1-2 minute. During this time only blackscreen. But system is booted, keyboard functions during this time.

**Comment by FC2714** [comment]
I fixed those issues by updating kexts in EFI folder with OC configurator.  Now I have question, I was using my bluetooth with Catalina to connect headphones. Now I can not turn on bluetooth in Monterey. I did not know whether I did use some fix for that in Catalina in order use bluetooth to connect speakers or headphones. Any Suggestions?

**Comment by GautamMakadia** [comment]
Which laptop model

**Comment by FC2714** [comment]
> Which laptop model

Legion Y530. Made some research found about BrcmPatch,Blutoolfix. But when I use those kexts I stuck on apple logo, system does not boot. I even activated my Wifi with openintelwireless kext. Cant find solution fot bluetooth. My wifi adapyer is Intel AC 3165. Bluetooth is shown as BRCM4350C2. I used some kexts such as AirportBrcmFix,Blutool,BrcmPatcRam3,BrcmDataFirmware. But last 3 does not let me boot. If I can make it boot maybe those 3 could help.

**Comment by xiaoMGitHub** [comment]
只需使用BlueToolFixup.kext和IntelBluetoothFirmware.kext

**Comment by FC2714** [comment]
> Just use BlueToolFixup.kext and IntelBluetoothFirmware.kext

I tried , but whenever I put BluToolFixup into kext folder of OC and Enable it from config.plist after restart it stucks on apple boot logo. No loading bar. Just Apple logo.
