### ISSUE TITLE
Wi-Fi & Bluetooth unavailable on Montery

### ISSUE THREAD

**Issue by Nurlan199206** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#221]
Wi-Fi not working after update to Monterey. Pls help

![image](https://user-images.githubusercontent.com/22808731/152872144-a9d60267-d67b-4bf0-ac71-558022ace327.png)

**Comment by xiaoMGitHub** [comment]
1、Make sure IntelBluetoothFirmware.kext v1.1.3 or newer is used.
2、Exclude the injection of IntelBluetoothInjector.kext for macOS Monterey from the Bootloader's config
3、Include BlueToolFixup.kext from [acidanthera/BrcmPatchRAM(opens new window)](https://github.com/acidanthera/BrcmPatchRAM)
