### ISSUE TITLE
Headphone-Jack(3.5mm) Issue (MACOS 12.5 UPDATE)

### ISSUE THREAD

**Issue by GautamMakadia** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#239]
After Updating to 12.5 the headphone starts producing noise.
Mode : Legion y540(9th gen).
Headphone Fix Is Applied.

I have tried removing and applying headphone fix but it still occurs.

**Comment by xiaoMGitHub** [comment]
try to update the kext

**Comment by GautamMakadia** [comment]
I Have Update kext.
Also reinstalled the os.

In windows works fine.

any other factors you knows why this happening? so, I raise issue in acidanthera kext repos.

**Comment by GautamMakadia** [comment]
Being fool 🤦 to understand that this is happening because of coil whine. 

So the fix is that use external dac to get rid of issue.("As Posting this, Still I haven't tested personally so, leaving this issue open until I test it out").
