### ISSUE TITLE
Lenovo Y540 (15IRH - 2019) - panic and some inactive devices

### ISSUE THREAD

**Issue by Akamajin** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#246]
Hello good people of China. Just wanted to report a few problems.
This is my laptop's variant:
CPU: i7 9750h
VGA: 1660

I managed to install and boot up macos Monterey on external ssd. but there are a few problems:
voodoo input kext (or something like that) causes panic. had to disable it before boot.
I'm not sure if optimization script worked. because touchpad, numpad and blutooth not working.
also didn't find a way to enable wifi.

but everything else worked smoothly. thanks for the great work.

**Comment by Akamajin** [comment]
Fix numpad:
https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/issues/86#issuecomment-627152268

Fix touchpad:
https://github.com/VoodooSMBus/VoodooRMI/releases/tag/1.3.4

Wi-Fi and blutooth fixed too. but can't remember wich kext solved the problem

**Comment by ivasuverma** [comment]
Hello Can you share your EFI folder?

**Comment by Akamajin** [comment]
> > Fix numpad:
> > [#86 (comment)](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/issues/86#issuecomment-627152268)
> > Fix touchpad:
> > https://github.com/VoodooSMBus/VoodooRMI/releases/tag/1.3.4
> > Wi-Fi and blutooth fixed too. but can't remember wich kext solved the problem
> 
> Can you share your EFI??

https://drive.google.com/file/d/1q8ehmY9YTHJTEeuH-4YMMSqo59gp0ybh/view?usp=sharing
