### ISSUE TITLE
Replace WIFI Card?

### ISSUE THREAD

**Issue by P4RS44** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#247]
Hi dear,
Can I replace the Y530 Realtek 8822BE WIFI card inside with BCM94360CD?

**Comment by xiaoMGitHub** [comment]
That's a good idea

**Comment by P4RS44** [comment]
> That's a good idea

Which WIFI card you suggest to replace instead of this one (None Apple)?

**Comment by xiaoMGitHub** [comment]
see [this](https://dortania.github.io/Wireless-Buyers-Guide/).

**Comment by P4RS44** [comment]
Thank you so much
