### ISSUE TITLE
Stuck in MacOS Ventura installer

### ISSUE THREAD

**Issue by P4RS44** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#249]
Hi dear,
When I am trying to install macos ventura, system stucks in booting usb installer.
I have no problem booting macos mojave, catalina and bigsur.
Can you help me please?

**Comment by RyanLu99** [comment]
if you wanna install macos ventura,you had better upgrade your OpenCore to 0.85 or above. you also need to upgrade your kexts

**Comment by parsapaknahad** [comment]
Thank you so much. I have updated to MacOS Ventura.
