### ISSUE TITLE
stuck boot on macOS Catalina

### ISSUE THREAD

**Issue by Qim10** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#45]
![WhatsApp Image 2019-12-14 at 9 55 37 PM](https://user-images.githubusercontent.com/58841774/70858747-c372ff80-1ebc-11ea-8015-7c2a68b029da.jpeg)
Hello I see Lenovo legion y530 but the booting stuck...but on macOS Mojave is not has problems

**Comment by xiaoMGitHub** [comment]
Refer to the installation [Guide](https://www.tonymacx86.com/threads/guide-lenovo-legion-y530-y540-laptop-on-catalina-10-15.288552/).
