### ISSUE TITLE
Error Optimise.sh

### ISSUE THREAD

**Issue by gopinet** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#46]
Hi, i have is error in terminal.

> Copy file to destination place...
> Chmod ALCPlugFix...
> Chmod localtime-toggle...
> Chmod org.osx86.localtime-toggle.plist...
> Load ALCPlugFix...
> Stopping existing ALCPlugFix daemon.
> /Library/LaunchDaemons/good.win.ALCPlugFix.plist: Operation now in progress
> /Library/LaunchDaemons/org.osx86.localtime-toggle.plist: Operation now in progress
> /Library/LaunchDaemons/org.virtualbox.startup.plist: Could not find specified service
> Load Localtime-toggle...
> Stopping existing localtime-toggle daemon.
> /Library/LaunchDaemons/org.osx86.localtime-toggle.plist: Operation now in progress
> Clear Cache...
> KernelCache ID: B7F7C80CA2DBB06EC3D7E1EDB577BCD7
> Kext with invalid signature (-67050) allowed: <OSKext 0x7fbe456b5410 [0x7fff8504d090]> { URL = "file:///Library/Apple/System/Library/Extensions/AppleUSBEthernetHost.kext/", ID = "com.apple.macos.driver.AppleUSBEthernetHost" }
> Done!

**Comment by xiaoMGitHub** [comment]
Try to execute it again, it may be normal.
