### ISSUE TITLE
No Audio on 3.0+ Legion y540

### ISSUE THREAD

**Issue by Angrycola222222** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#49]
I rolled back to 2.0.3 EFI because every version above makes the audio output disappear. Also brightness controll with the fn key is missing in 3.0+ 

I am using the Lenovo Legion Y540 i7/rtx2060 version
MacOS Catalina 15.0.1

**Comment by xiaoMGitHub** [comment]
Sound problems can be resolved by restarting. Backlight control can try to replace the[ voodoops2 ](https://github.com/acidanthera/VoodooPS2)

**Comment by oniharnantyo123** [comment]
i am using version 3.0.2 and face this problem, then i injected layout id with 18 referenced on https://github.com/acidanthera/AppleALC/releases and problem solved.
