### ISSUE TITLE
Wireless card suggestion

### ISSUE THREAD

**Issue by ASparkOfFire** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#50]
Hey, I am Thinking to install Mac OS on my Legion Y540, I want to ask if this WiFi card will work.

https://tinyurl.com/yz3nxhhv

It is BCM94352Z AE

Unfortunately, there are very few options for me to buy from. Please check if this card will work.

**Comment by xiaoMGitHub** [comment]
The use of DW1820A is not recommended, and there are many small problems.

**Comment by ASparkOfFire** [comment]
Thanks for replying, can you suggest me another card? If possible please provide a link.

**Comment by xiaoMGitHub** [comment]
You can purchase DW1560, DW1830, BCM94360cs2 and BCM943602cs.

**Comment by liho00** [comment]
Hi, If i want to triple boot this machine including hackintosh, windows and linux, which wifi is the best and suitable? Thanks in advance!

**Comment by xiaoMGitHub** [comment]
@liho00 I suggest you buy dw1560.

**Comment by liho00** [comment]
![image](https://user-images.githubusercontent.com/34411102/73188397-c7ea3380-415d-11ea-93fc-76bd669b2d21.png)

But why you are suggesting BCM943602cs? what is the difference between BCM943602cs and dw1560 bcm94352Z ? thanks in advance!

**Comment by ASparkOfFire** [comment]
@liho00 BCM943602CS won't physically fit into the m.2 slot. It's a Mini PCIe card. You need adapter and extension cable, which you'll have to cram up in the already less available space. better option is to get a DW1560, I've ordered one from AliExpress, waiting for it to ship.

**Comment by liho00** [comment]
> @liho00 BCM943602CS won't physically fit into the m.2 slot. It's a Mini PCIe card. You need adapter and extension cable, which you'll have to cram up in the already less available space. better option is to get a DW1560, I've ordered one from AliExpress, waiting for it to ship.

How much did you bought? Could you kindly provide me the aliexpress link? thanks in advance!

**Comment by ASparkOfFire** [comment]
@liho00 Get it from where you find the cheapest, I paid about 50 USD for it.

**Comment by ASparkOfFire** [comment]
@xiaoMGitHub Friend, I need your help. I couldn't get iMessage and FaceTime to work. I've tried everything still can't get them to work. Please help

**Comment by ASparkOfFire** [comment]
Nevermind, after doing some deep research and help from Telegram group, I got iMessage and FaceTime to Work, Thank you so much for your work.
