### ISSUE TITLE
睡眠有时候五国

### ISSUE THREAD

**Issue by pinkpeachabc** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#51]
您好，本人使用您制作的efi文件成功的装上了10.14.6，在使用的过程中笔记本待机睡眠时候鼠标和键盘不能唤醒电脑 开机键可以唤醒 ，并且有时候待机睡眠时间长了再次按开机键唤醒会自动重启出现五国。请问这是什么问题？谢谢

**Comment by xiaoMGitHub** [comment]
严格执行EFI使用说明
