### ISSUE TITLE
8代触摸盘功能不全

### ISSUE THREAD

**Issue by bbstaima** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#53]
黏贴了你的EFI文件，触摸板目前只能移动不能点击。修改SSDT-I2C文件不能编译，有很多错误。请问该如何解决。

**Comment by xiaoMGitHub** [comment]
能移动不能点击，自己去设置里面设置点击就行了。ssdt-I2c文件修改，需要在表头引用变量，这是编程基础
