### ISSUE TITLE
Stuck on boot Lenovo Y530

### ISSUE THREAD

**Issue by deounix** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#55]
I've tried every single method available to install macOS Catalina on Lenovo Y530 but it always stuck on booting. is there any a step by step guide to install it?

I try this guide also:

[Guide](https://www.tonymacx86.com/threads/guide-lenovo-legion-y530-y540-laptop-on-catalina-10-15.288552/
)

nothing work.

**Comment by xiaoMGitHub** [comment]
In win / macOS / shutdown state, press FN + o + d at the same time, and then modify Advanced> Debug settings> Kernel Debug Serial Port to Leagacy UART

**Comment by deounix** [comment]
@xiaoMGitHub Thank you I didn't notice this step.

So after doing this should I copy both: (ACPI - folder && config-Clover.plist - file) to my USB?
Or just doing normal Catalina installation than after am I inside my mac I'll do: `sudo sh -c "$(curl -fsSL https://gitee.com/xiaoMGit/Y7000Series_Hackintosh_Fix/raw/master/Script/Optimize.sh)"`

Sorry but I am a bit new to Hackintosh. Thnx.

**Comment by xiaoMGitHub** [comment]
@deounix It is recommended that you use version 3.0.1.

**Comment by deounix** [comment]
it works. 🤩🤩🤩

So in EFI you should remove both folders. then you must copy& paste your folders

At my first try I replace them thrn errors happend.

Legions thanks you
