### ISSUE TITLE
安装时找不到内置nvme硬盘 可以找到机械硬盘 硬盘不是三星PM981 

### ISSUE THREAD

**Issue by funnybluecat** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#56]

**Comment by funnybluecat** [comment]
Y7000 硬盘是 镁光

**Comment by xiaoMGitHub** [comment]
首先y7000-2019款自带镁光是无法安装的，当然你可以使用我提供的热补丁 SSDT-DNVME.aml 来屏蔽（你应该是已经使用了，否则你无法进入安装界面），镁光这个盘比较坑，建议更换或者添加一个新的sata固态进行安装。

**Comment by liho98** [comment]
> 首先y7000-2019款自带镁光是无法安装的，当然你可以使用我提供的热补丁 SSDT-DNVME.aml 来屏蔽（你应该是已经使用了，否则你无法进入安装界面），镁光这个盘比较坑，建议更换或者添加一个新的sata固态进行安装。

请问您可以推荐那个sata固态和pcie m.2 nvme固态比较好吗？（我打算把原有的1个固态和1个hdd给换了）

听说三星 970 evo性能好但不知适不适合联想军团y530，还有intel ssd 770p，有点难选择。。。

**Comment by xiaoMGitHub** [comment]
> > 首先y7000-2019款自带镁光是无法安装的，当然你可以使用我提供的热补丁 SSDT-DNVME.aml 来屏蔽（你应该是已经使用了，否则你无法进入安装界面），镁光这个盘比较坑，建议更换或者添加一个新的sata固态进行安装。
> 
> 请问您可以推荐那个sata固态和pcie m.2 nvme固态比较好吗？（我打算把原有的1个固态和1个sata hdd给换去固态）
> 
> 还有我想要triple boot这台机器包括windows，mac和linunx。
> 
> 听说三星 970 evo性能好但不知适不适合联想军团y530，还有intel ssd 770p，有点难选择。。。

我对ssd没深入研究，一般我只推荐 intel 760p，主要是发热量低，黑苹果对nvme的支持不好
