### ISSUE TITLE
No Complete EFI

### ISSUE THREAD

**Issue by RaviKavaiya** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#57]
@xiaoMGitHub Since version 3.0.1, you are not giving complete EFI.
I want 3.0.2 complete EFI.
Also, I don't have acces to 'QQ' .
So, please post latest and complete EFI.

**Comment by gauravsaini964** [comment]
@xiaoMGitHub Please provide it here for y530, we cannot join QQ..

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub

**Comment by liho98** [comment]
在马来西亚，我创建不到qq

**Comment by xiaoMGitHub** [comment]
It will be updated later.

**Comment by liho98** [comment]
> It will be updated later.

thanks!

**Comment by RaviKavaiya** [comment]
@xiaoMGitHub  One more issue!
When using ACPI files of v3.0.2, the Keyboard stops working. I can't even Login in macOS. (Mojave - 10.14)

**Comment by xiaoMGitHub** [comment]
> @xiaoMGitHub One more issue!
> When using ACPI files of v3.0.2, the Keyboard stops working. I can't even Login in macOS. (Mojave - 10.14)

Use voodooPS2 keyboard driver.

**Comment by RaviKavaiya** [comment]
> > @xiaoMGitHub One more issue!
> > When using ACPI files of v3.0.2, the Keyboard stops working. I can't even Login in macOS. (Mojave - 10.14)
> 
> Use voodooPS2 keyboard driver.

I did not understand. Can you please elaborate? You talking about kext?

**Comment by gauravsaini964** [comment]
@xiaoMGitHub Please release EFI folder for y530, waiting since ages...
