### ISSUE TITLE
升级10.15.3没法用小键盘

### ISSUE THREAD

**Issue by 2O48** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#58]
执行了efi里的开启小键盘代码显示404，之前的一个numlock程序也出了问题，请作者更新一下！

**Comment by xiaoMGitHub** [comment]
小键盘那块不是由我维护，有需要可以使用群里的EFI，所有功能一切正常

**Comment by liho98** [comment]
> 小键盘那块不是由我维护，有需要可以使用群里的EFI，所有功能一切正常

请问有链接吗？因为无法注册qq。。

**Comment by liho98** [comment]
![96FA39F1-5810-4BB1-AF3C-D1668F788E8C](https://user-images.githubusercontent.com/44250267/74889372-cb1ebb00-53bb-11ea-97a0-b182b8c96fc1.png)

@xiaoMGitHub 幫幫我好嗎🥺

**Comment by xiaoMGitHub** [comment]
@liho98 最近我正打算编写一个自动生成EFI的脚本，但由于我的网络问题我无法访问bitbucket获取部分kext，如果用兴趣可以添加QQ：3448951991，帮忙调试。

**Comment by liho98** [comment]
> @liho98 最近我正打算编写一个自动生成EFI的脚本，但由于我的网络问题我无法访问bitbucket获取部分kext，如果用兴趣可以添加QQ：3448951991，帮忙调试。

可以，我的网络可以访问bitbucket，我可以帮你。

**Comment by ASparkOfFire** [comment]
@xiaoMGitHub I can't join QQ I'm from India please help. I'm willing to help you with EFI

**Comment by xiaoMGitHub** [comment]
> @xiaoMGitHub I can't join QQ I'm from India please help. I'm willing to help you with EFI

I am writing a script that automatically generates EFI and will release it soon.
