### ISSUE TITLE
外接显示器

### ISSUE THREAD

**Issue by Shiyang-Wang** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#59]
请问Y7000 typec口或mini dp口黑苹果下能外接显示器吗？还是和独立显卡直连不能用？

**Comment by xiaoMGitHub** [comment]
除了USB转HDMI，似乎没找到其他的方式。对了，隔空播放可以投屏。

**Comment by zxp1314gch** [comment]
> 除了USB转HDMI，似乎没找到其他的方式。对了，隔空播放可以投屏。

typec转HDMI可以吗？
