### ISSUE TITLE
請問下 Y545 i5/1660ti 能兼容嗎

### ISSUE THREAD

**Issue by Pablolusong** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#60]
您好 我在考慮買一台y545 (台版的y7000p) i5 1660ti 144Hz，不知道和內地的y7000p 同配置的相容性如何？

**Comment by xiaoMGitHub** [comment]
@Pablolusong 理论上是兼用的，内地今年新出的2019款y7000p的配置跟y545是一样

**Comment by Pablolusong** [comment]
> @Pablolusong 理论上是兼用的，内地今年新出的2019款y7000p的配置跟y545是一样

感謝大神 話說小的家裡有台MacBook Pro 13” 2015 原廠網卡就是BCM943602CS，那運行Windows 的時候會有什麼異常嗎？

**Comment by xiaoMGitHub** [comment]
> > @Pablolusong 理论上是兼用的，内地今年新出的2019款y7000p的配置跟y545是一样
> 
> 感謝大神 話說小的家裡有台MacBook Pro 13” 2015 原廠網卡就是BCM943602CS，那運行Windows 的時候會有什麼異常嗎？

不会，我目前使用的就是BCM943602CS，win和OSX下一切正常
