### ISSUE TITLE
SK Hynix NVMe SSD is not detected

### ISSUE THREAD

**Issue by dimka3553** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#61]
My Legion Y540 arrived with a SK Hynix SSD, and it does not show up in the disk utility, how can I fix it?

**Comment by xiaoMGitHub** [comment]
Storage mode: AHCI

**Comment by dimka3553** [comment]
Yes, It is on AHCI and is undetected

**Comment by xiaoMGitHub** [comment]
Did you add SSDT-DNVME.aml hotpatch?

**Comment by dimka3553** [comment]
Yes

**Comment by xiaoMGitHub** [comment]
SSDT-DNVME.aml is mainly used to shield nvme interface. I'm sorry to tell you that the SK Hynix NVMe SSD carried by the y540 cannot be used to install Hackintosh.

**Comment by oniharnantyo123** [comment]
i wonder why i can't find oem ssd on installation. So, just add SATA ssd.

**Comment by meendoo** [comment]
I replaced SK Hynix SSD with a Corsair Force MP510, cause I wasn't able to make it work.
