### ISSUE TITLE
睡眠半小时后系统崩溃重启，数字键盘仍有缺陷

### ISSUE THREAD

**Issue by Mr-UFO** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#62]
十分感谢作者发布的内容，不过我仍遇到一些问题：
1.睡眠大约30～60min系统崩溃，重启，进入clover界面。不管是否盒盖都会有这个问题。此时若不及时发现，必须等到电池完全耗尽才能自动关机。开机显示的提示信息如图所示。
![F0AD36BD9DA5DCE213F673872FDBA3FA](https://user-images.githubusercontent.com/59684700/75570661-8d442580-5a92-11ea-9979-2ce832d1addb.jpg)

百度查了许多都没有有用的信息。
2.数字键盘仍有缺陷。在执行优化命令后，必须在clover引导界面将numlock灯点亮才能使用数字键盘。进入系统后，不能关闭numlock导致无法使用“4”“5”“6”“*”键从而控制歌曲的播放。而且，一个更大的缺陷是：numlock和capsLK不能同时使用，即一旦打开capslk，除非重启，将不能使用数字键盘。
系统已经重装了好几遍了，这些问题依旧存在。求大神解答，谢谢。
配置：y7000-2019，1650，8g，安装在256g860evo，目前10.15.3

**Comment by Mr-UFO** [comment]
![E75B75A931CD04347B68190252A3AFE3](https://user-images.githubusercontent.com/59684700/75571294-db0d5d80-5a93-11ea-805e-f89cd4b041b3.jpg)
上一张图不清楚，重贴一张

**Comment by xiaoMGitHub** [comment]
至于你说的，群里大佬发布的EFI都已经解决，建议使用3.0.2进行尝试

**Comment by lx200916** [comment]
睡眠中崩溃重启3.02也会出现

**Comment by xiaoMGitHub** [comment]
> 睡眠中崩溃重启3.02也会出现

目前没有收到群友反馈3.0.2存在睡眠问题，建议检测EFI是否正确

**Comment by AlwaysZmx** [comment]
> > 睡眠中崩溃重启3.02也会出现
> 
> 目前没有收到群友反馈3.0.2存在睡眠问题，建议检测EFI是否正确

我也遇到了同样的问题，机型一样

**Comment by Mr-UFO** [comment]
clover睡眠有严重缺陷；
睡眠换oc之后崩溃概率1%；数字键盘驱动方法在群里有，不方便说，毕竟是付费群…………

**Comment by Mr-UFO** [comment]
clover睡眠有缺陷；
睡眠换oc之后崩溃概率1%；数字键盘驱动方法在群里有，不方便说，毕竟是付费群………… 
@AlwaysZmx

**Comment by Mr-UFO** [comment]
所有睡眠问题，换oc应该是正解

**Comment by Mr-UFO** [comment]
#86 @AlwaysZmx

**Comment by qixiaoleng** [comment]
解决了没老哥 发一下efi

**Comment by ammi3** [comment]
> 所有睡眠问题，换oc应该是正解

所以说老哥最后换的OC解决了问题？还是通过其他方法解决的

**Comment by Mr-UFO** [comment]
我是提问者。换oc崩溃的概率确实小了
________________________________

**Comment by ammi3** [comment]
> > > 睡眠中崩溃重启3.02也会出现
> > 
> > 
> > 目前没有收到群友反馈3.0.2存在睡眠问题，建议检测EFI是否正确
> 
> 我也遇到了同样的问题，机型一样

大哥解决了吗？
