### ISSUE TITLE
my laptop is thinkpad s5 with i5-6300hq.

### ISSUE THREAD

**Issue by CrazyIEEE** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#63]
i use you opencore efi.no sound.and screen memony is 7m.
so i chang use hd530 id and use true layout is for sound.
i found that , memony is true 2048m but no voice,
and i return hd630 use true layout , screen memony is 7m.but voice is ok.
so, use video memony and voice can not be use each other.

i want know the methed

thanks :)

**Comment by CrazyIEEE** [comment]
may is problem with lilu and greedware ???

**Comment by xiaoMGitHub** [comment]
I don't have a thinkpad s5, so I can't help you.
