### ISSUE TITLE
clover替换成oc的问题

### ISSUE THREAD

**Issue by HXChow** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#65]
18款y7000 改了bios上了15的系统 现在想把clover换成oc ，请问是不是只需将文件直接替换就好了不用改动其他的设置

**Comment by xiaoMGitHub** [comment]
整个EFI替换即可，然后清理下nvram

**Comment by HXChow** [comment]
> 整个EFI替换即可，然后清理下nvram

请问该如何清理nvram呢

**Comment by xiaoMGitHub** [comment]
OC引导界面就有清理选项

**Comment by HXChow** [comment]
> OC引导界面就有清理选项

也就是说替换完后进入引导就清理即可是吧
谢谢您的解答
