### ISSUE TITLE
Y540, i5 9300H , GTX 1650

### ISSUE THREAD

**Issue by Raeesreyi** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#66]
Black screen after selecting Install macOS in clover, then shutting down automatically.
Done evrything as in forum, they banned my account for no reason. 
Bios settings
AHCI
Secureboot disabled.

**Comment by xiaoMGitHub** [comment]
Restart from windows to enter the BIOS settings and change the Graphic Device in the Configuration to Switchable Graphics.

**Comment by Raeesreyi** [comment]
> Restart from windows to enter the BIOS settings and change the Graphic Device in the Configuration to Switchable Graphics.

I did it yesterday itself and result was,
Clover booted-selected Install macOS- Apple logo loaded half and shown the welcome agreement screen. So I eerased and selected mac os extended journal as format in Disk Utilities. Right after selecting my drive for installation, Shut down itself. 
Tried Again, This time I didn't get time to reach out disk utilities. Shut down on agreement screen.

So I reflashed it and did again expecting it to install. Result were same.
During these Installation I managed to change the USB ports, to make sure no problem in that. 

What did I do wrong.

**Comment by Raeesreyi** [comment]
May be the issue is with the osX dmg file I have. Can you give out any downloadable link for that. Or can be done only by accessing another macBook?

**Comment by Raeesreyi** [comment]
Update. @xiaoMGitHub 
I did flash the drive with other dmg file and replaced clover to 3.0.1 from the site and booted. Installation from USB to SSD went very well without an issue. I was very Happy.
Then restarted itself and selected installation from SSD and this time it restarted in the middle of installation saying restarted because of a problem, I hope its because of kernel issues. what should I do to get it work. I eagerly want macOS in my machine. It will be a great thing for me if it get working.

**Comment by xiaoMGitHub** [comment]
Under normal circumstances, the installation process will automatically restart twice without any intervention.

**Comment by Raeesreyi** [comment]
> Under normal circumstances, the installation process will automatically restart twice without any intervention.
@xiaoMGitHub 

Thats what I thought but then after selecting install from ssd again it starts installation from the start and again restarts saying because of a problem/ after a panic in verbose mode. Is there a change to be done in config.plist. I searched everywhere to edit it in windows, no luck. Please assist me. I'm using clover 3.0.2.

[CLOVER.zip](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/files/4425228/CLOVER.zip)

**Comment by Raeesreyi** [comment]
I'm hoping a message from you. Im in  trouble.

**Comment by xiaoMGitHub** [comment]
Alternatively, you can send me an email to contact me, github's email reminder system seems to be delayed. zxmyhd@163.com

**Comment by Raeesreyi** [comment]
> Alternatively, you can send me an email to contact me, github's email reminder system seems to be delayed. [zxmyhd@163.com](mailto:zxmyhd@163.com)

I mailed you brother. It will be great if you check it.
