### ISSUE TITLE
Please release 3.0.2 efi folder for legion y530.

### ISSUE THREAD

**Issue by gauravsaini964** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#67]
@xiaoMGitHub We cannot join QQ group, I am happy to donate but QQ is not easy to signup on.
I can easily donate via paypal but please provide new EFI, been waiting for too long.

Thanks

**Comment by xiaoMGitHub** [comment]
At present, 3.0.1 can meet all the functions, and 3.0.2 is expected to be uploaded after the release of OpenCore 1.0.0.

**Comment by TheSenseiRyu** [comment]
> At present, 3.0.1 can meet all the functions, and 3.0.2 is expected to be uploaded after the release of OpenCore 1.0.0.

Hi, i want to donate and participate for testing to but i cannot create a qq account (my phone number is refused, im from France), is there any other way to contact/donate you such as paypal? And ive a little question , is opencore better than clover ? Should i switch from clover to it ? Thanks in advance for any reply ^^ thanks too for your hard work
