### ISSUE TITLE
No audio after 10.15.4 update

### ISSUE THREAD

**Issue by ucristian3** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#69]
hello! I dont know what to do anymore,everything works except audio .
I did put the "setleds" file in privacy/accesibility setting and changed layout it to 18 still no not working.
thank you.

**Comment by theMonk3y** [comment]
> hello! I dont know what to do anymore,everything works except audio .
> I did put the "setleds" file in privacy/accesibility setting and changed layout it to 18 still no not working.
> thank you. 

In clover configurator open config.plist navigate to devices end set Audio inject to detect.

**Comment by ucristian3** [comment]
> > hello! I dont know what to do anymore,everything works except audio .
> > I did put the "setleds" file in privacy/accesibility setting and changed layout it to 18 still no not working.
> > thank you.
> 
> In clover configurator open config.plist navigate to devices end set Audio inject to detect or try set it to 13, on my y530 both settings working same.
> And update your kexts.

Still not working man,I dont know what happens,you a have some other ideas?

**Comment by theMonk3y** [comment]
> > > hello! I dont know what to do anymore,everything works except audio .
> > > I did put the "setleds" file in privacy/accesibility setting and changed layout it to 18 still no not working.
> > > thank you.
> > 
> > In clover configurator open config.plist navigate to devices end set Audio inject to detect or try set it to 13, on my y530 both settings working same.
> > And update your kexts.
> 
> Still not working man,I dont know what happens,you a have some other ideas?

It's working on windows? Try it. 
I think it's doesn't work on windows too . 
I have the same problem 1 week ago . 
Try it and tell me.

**Comment by ucristian3** [comment]
In windows works without problems, never had problems with audio on windows

**Comment by theMonk3y** [comment]
> In windows works without problems, never had problems with audio in windows

You try it now? 
I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything. 
If you doesn't have this problem , I can give you my EFI to try if you want . 
It's fully working with audio numpad etc.

**Comment by ucristian3** [comment]
> > In windows works without problems, never had problems with audio in windows
> 
> You try it now?
> I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything.
> If you doesn't have this problem , I can give you my EFI to try if you want .
> It's fully working with audio numpad etc.

my laptop is Y540 9300h/32gb/1660Ti  will it work?

**Comment by theMonk3y** [comment]
> > > In windows works without problems, never had problems with audio in windows
> > 
> > You try it now?
> > I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything.
> > If you doesn't have this problem , I can give you my EFI to try if you want .
> > It's fully working with audio numpad etc.
> 
> my laptop is Y540 9300h/32gb/1660Ti  will it work?

I think yes . I have the same EFI with same kexts from Xiaom. Just updated to latest versions (kexts and clover) and with all scripts from Xiaom installed. 
remember me tommorow at morning for the link . 
I'm not at home now!
We will try to find solution.

**Comment by ucristian3** [comment]
> > > > In windows works without problems, never had problems with audio in windows
> > > 
> > > 
> > > You try it now?
> > > I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything.
> > > If you doesn't have this problem , I can give you my EFI to try if you want .
> > > It's fully working with audio numpad etc.
> > 
> > 
> > my laptop is Y540 9300h/32gb/1660Ti  will it work?
> 
> I think yes . I have the same EFI with same kexts from Xiaom. Just updated to latest versions (kexts and clover) and with all scripts from Xiaom installed.
> remember me tommorow at morning for the link .
> I'm not at home now!
> We will try to find solution.

Alright ,see you tomorow morning and thank for everything!

**Comment by TheSenseiRyu** [comment]
> > > > In windows works without problems, never had problems with audio in windows
> > > 
> > > 
> > > You try it now?
> > > I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything.
> > > If you doesn't have this problem , I can give you my EFI to try if you want .
> > > It's fully working with audio numpad etc.
> > 
> > 
> > my laptop is Y540 9300h/32gb/1660Ti  will it work?
> 
> I think yes . I have the same EFI with same kexts from Xiaom. Just updated to latest versions (kexts and clover) and with all scripts from Xiaom installed.
> remember me tommorow at morning for the link .
> I'm not at home now!
> We will try to find solution.

hi sorry but ive the exact same probleme with the exact same p, can i have it too i you have the time to send it to me ? Thanks in advance for any reply

**Comment by theMonk3y** [comment]
> > > > > In windows works without problems, never had problems with audio in windows
> > > > 
> > > > 
> > > > You try it now?
> > > > I ask you because 3 days ago I have problem with my soundcard, it's freeze when I boot to Mac, I don't know why but it's stops working on both systems. Solution for this is power off the laptop, open and disconnect battery and bios battery for 10 minutes , press the power button for 15 sec to discharge all motherboard and reconnect again everything.
> > > > If you doesn't have this problem , I can give you my EFI to try if you want .
> > > > It's fully working with audio numpad etc.
> > > 
> > > 
> > > my laptop is Y540 9300h/32gb/1660Ti  will it work?
> > 
> > I think yes . I have the same EFI with same kexts from Xiaom. Just updated to latest versions (kexts and clover) and with all scripts from Xiaom installed.
> > remember me tommorow at morning for the link .
> > I'm not at home now!
> > We will try to find solution.
> 
> hi sorry but ive the exact same problem with the exact same pc, can i have it too if you have the time to send it to me ? Thanks in advance for any reply

Ok. At morning. 

Try this too guys . 
https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/issues/49#issuecomment-593467638

**Comment by TheSenseiRyu** [comment]
Big thanks, im already on 18layout and latest kexts, dont know why itsnt working properly.

**Comment by xiaoMGitHub** [comment]
The sound problem can only be solved by restarting, it is recommended to use layout = 18

**Comment by ucristian3** [comment]
> The sound problem can only be solved by restarting, it is recommended to use layout = 18


restarted it more than a thousand times already i think.. something must be wrong with the EFI or the system.

**Comment by ucristian3** [comment]
BREAKING: hackintool says me that i have to update my open core bootloader when im using Clover. WTF?

**Comment by xiaoMGitHub** [comment]
> > The sound problem can only be solved by restarting, it is recommended to use layout = 18
> 
> restarted it more than a thousand times already i think.. something must be wrong with the EFI or the system.

Or you can follow this [AppleALC working intermittently](https://github.com/acidanthera/bugtracker/issues/422).

**Comment by theMonk3y** [comment]
> BREAKING: hackintool says me that i have to update my open core bootloader when im using Clover. WTF?

MY EFI: 
https://mega.nz/file/thhyhCgB#oJ1pgoUDdKgzC3tC4x5tsEP6yw5ugFChCR6-oWlzNEQ

try it.. maybe it works.

**Comment by ucristian3** [comment]
> > BREAKING: hackintool says me that i have to update my open core bootloader when im using Clover. WTF?
> 
> MY EFI:
> https://mega.nz/file/thhyhCgB#oJ1pgoUDdKgzC3tC4x5tsEP6yw5ugFChCR6-oWlzNEQ
> 
> try it.. maybe it works.
> on my machine Works good. Touchpad , sound, numepad etc.

I tried and its working just like my EFI ,stii no audio ...but the problem is why hackintool is still telling me that I have opencore installed

**Comment by theMonk3y** [comment]
> > > BREAKING: hackintool says me that i have to update my open core bootloader when im using Clover. WTF?
> > 
> > 
> > MY EFI:
> > https://mega.nz/file/thhyhCgB#oJ1pgoUDdKgzC3tC4x5tsEP6yw5ugFChCR6-oWlzNEQ
> > try it.. maybe it works.
> > on my machine Works good. Touchpad , sound, numepad etc.
> 
> I tried and its working just like my EFI ,stii no audio ...but the problem is why hackintool is still telling me that I have opencore installed

interesting. what is your soundcard codec??

**Comment by ucristian3** [comment]
> > > > BREAKING: hackintool says me that i have to update my open core bootloader when im using Clover. WTF?
> > > 
> > > 
> > > MY EFI:
> > > https://mega.nz/file/thhyhCgB#oJ1pgoUDdKgzC3tC4x5tsEP6yw5ugFChCR6-oWlzNEQ
> > > try it.. maybe it works.
> > > on my machine Works good. Touchpad , sound, numepad etc.
> > 
> > I tried and its working just like my EFI ,stii no audio ...but the problem is why hackintool is still telling me that I have opencore installed
> 
> interesting. what is your soundcard codec?? 
> 
> https://noobsplanet.com/index.php?threads/applealc-supported-codecs-for-hackintosh.329/
> 
> Find what ALC is your soundcard and try the Revisions.
> 
> (how to find your codec: https://imgur.com/afLOGfW )

It's ALC257, Which revision to try?

**Comment by theMonk3y** [comment]
Revision 11 
screenshot: https://imgur.com/KAcTnRp 

put audio inject **11** , save and restart your system! 
go to audio settings and check output devices.

**Comment by ucristian3** [comment]
> Revision 11 
> screenshot: https://imgur.com/KAcTnRp 
> 
> put audio inject **11** , save and restart your system! 
> go to audio settings and check output devices.
> 
> Changed EFI: https://mega.nz/file/ExQhGQbY#gA-8Vns9zpU21s7WrDiVCgFvvwxRo9CPjFC3JOTFhBA
> 
> check this too : https://www.hackintosh-forum.de/forum/thread/26775-applealc-der-dynamische-applehda-patcher-immer-aktuell/?pageNo=2

Tried the changed EFI whit the ID 11,same thing

**Comment by theMonk3y** [comment]
> > Revision 11 
> > screenshot: https://imgur.com/KAcTnRp 
> > 
> > put audio inject **11** , save and restart your system! 
> > go to audio settings and check output devices.
> > 
> > Changed EFI: https://mega.nz/file/ExQhGQbY#gA-8Vns9zpU21s7WrDiVCgFvvwxRo9CPjFC3JOTFhBA
> > 
> > check this too : https://www.hackintosh-forum.de/forum/thread/26775-applealc-der-dynamische-applehda-patcher-immer-aktuell/?pageNo=2
> 
> Tried the changed EFI whit the ID 11,same thing

check this too : https://www.hackintosh-forum.de/forum/thread/26775-applealc-der-dynamische-applehda-patcher-immer-aktuell/?pageNo=2

**Comment by ucristian3** [comment]
I found another solution to fix this by intalling this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15  and guess what...ITS WORKING without problems

**Comment by theMonk3y** [comment]
> I found another solution to fix this by intalling this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15  and guess what...ITS WORKING without problems

Good news!! ✊

**Comment by ucristian3** [comment]
> > I found another solution to fix this by intalling this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15  and guess what...ITS WORKING without problems
> 
> Good news!! ✊

Thanks for your help buddy 👍

**Comment by xiaoMGitHub** [comment]
> > I found another solution to fix this by intalling this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15  and guess what...ITS WORKING without problems
> 
> Good news!! ✊

Compared to VoodooHDA, I prefer to use AppleALC, haha

**Comment by ucristian3** [comment]
> > > I found another solution to fix this by intalling this https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V15  and guess what...ITS WORKING without problems
> > 
> > Good news!! ✊
> 
> Compared to VoodooHDA, I prefer to use AppleALC, haha

I understand. In my case I wasn't able to fix AppleALC .Good that there are other ways. Thank you

**Comment by gauravsaini964** [comment]
@xiaoMGitHub @ucristian3  AppleALC 1.4.8 with alcdelay=500(ms) works perfect on default 3.0.2 config. Audio works every-time on every boot.

**Comment by xiaoMGitHub** [comment]
> @xiaoMGitHub @ucristian3 AppleALC 1.4.8 with alcdelay=500(ms) works perfect on default 3.0.2 config. Audio works every-time on every boot.

Unfortunately, after testing by hundreds of users, this parameter has no effect.
