### ISSUE TITLE
HDMI Solution - External Monitor

### ISSUE THREAD

**Issue by theMonk3y** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#70]
Good morning Xiaom! 
Thank you for your hard work. 
-
I read many forums to find solution for this.
People say about **USB3.0 to HDMI**.
Have you tried ?

**Comment by Foldblade** [comment]
I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.

**Comment by theMonk3y** [comment]
> I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.

little bit expensive but good news!! 
you can extend displays or only mirror? 
and you connect HDMI via DVI to HDMI adapter?? becaus i see its no HDMI port on this dock.
what about resolution and hz ?? 1080 60hz ? 

thank you friend.

**Comment by Foldblade** [comment]
> 
> 
> > I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.
> 
> little bit expensive but good news!!
> you can extend displays or only mirror?
> and you connect HDMI via DVI to HDMI adapter?? becaus i see its no HDMI port on this dock.
> what about resolution and hz ?? 1080 60hz ?
> 
> thank you friend.

I'm now at 10.15.3 with the newest DisplayLink driver, and I can extend the displays.
Just as you said, I connect HDMI via a DVI-I to HDMI adapter.
I once connected my computer to a 1080P display successfully, but I don't know its refresh rate...

**Comment by theMonk3y** [comment]
> > > I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.
> > 
> > 
> > little bit expensive but good news!!
> > you can extend displays or only mirror?
> > and you connect HDMI via DVI to HDMI adapter?? becaus i see its no HDMI port on this dock.
> > what about resolution and hz ?? 1080 60hz ?
> > thank you friend.
> 
> I'm now at 10.15.3 with the newest DisplayLink driver, and I can extend the displays.
> Just as you said, I connect HDMI via a DVI-I to HDMI adapter.
> I once connected my computer to a 1080P display successfully, but I don't know its refresh rate...

if its comfortable to use for you i think its 60hz . 
thank you for you info bro! if i dosent find something cheeper i will try this dock!

**Comment by RaviKavaiya** [comment]
@Foldblade what is DisplayLink driver?

**Comment by Foldblade** [comment]
@RaviKavaiya 
According to [this comment]( https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/issues/10#issuecomment-485372340), you should choose a USB to HDMI adapter which supports [DisplayLink](https://www.displaylink.com/).

**Comment by theMonk3y** [comment]
so i found many adapters with displaylink on normal prices (just adapter no dock)
if somebody want to purchase read carefully description about sound and compatibility with 10.15 first. 
Many of this adapters dosent transfer audio via HDMI.

**Comment by elhm** [comment]
> I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.

Did it work out od the box? Any drivers were required for mac os? In manual they say it only has windows drivers.

**Comment by Foldblade** [comment]
> 
> 
> > I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.
> 
> Did it work out od the box? Any drivers were required for mac os? In manual they say it only has windows drivers.

You need to download and install a driver for macOS from [here](https://www.displaylink.com/downloads/macos).

**Comment by elhm** [comment]
> > > I purchased a [Lenovo Thinkpad USB 3.0 Dock](https://support.lenovo.com/dk/da/solutions/pd023761), works good for me.
> > 
> > 
> > Did it work out od the box? Any drivers were required for mac os? In manual they say it only has windows drivers.
> 
> You need to download and install a driver for macOS from [here](https://www.displaylink.com/downloads/macos).

Thanks man, that's very helpful.
