### ISSUE TITLE
random reboot

### ISSUE THREAD

**Issue by TheSenseiRyu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#71]
Hi, first of all, thx for all you hard work in this project that permit me to have macOS to use it as student. So, my problem is when I let my pc on safari page, for exemple, and go to eat, when I return, I saw my pc in clover boot loader and when i return to macOS it saying me that my Mac crash because of a problem. Same thing happen when i close the lap of my laptop and let it go to sleep for several hours, when i open it it restart and when i go to macos it saying me that my mac have reboot because of a problem... Its pretty annoying because i have to shutdown my laptop everytime i need to go somewhere to prevent unsaved work to be lost. I have stock latest public clover efi, command executed, everything work : sound (solved by downgrade to mojave), numpad,70% trackpad and macos mojave recently clean reinstall. Before i was on latest catalina and updated but same thing had happened several times in the past in this os too. Thanks in advance for any reply.
PS: My laptop is lenovo legion y540 with 16gb ram, i5 9e gen and rtx 2060
edit : second PS: sorry if its not really clear, im fench

**Comment by xiaoMGitHub** [comment]
Upload your [PR report](https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/).

**Comment by TheSenseiRyu** [comment]
Thanks, but need i to reproduce the bug and after to generate a PR report or doing it right now ?

**Comment by xiaoMGitHub** [comment]
Just execute immediately.
