### ISSUE TITLE
Y7000 2018 开启触摸板GPIO失败

### ISSUE THREAD

**Issue by alexlipe** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#74]
Y7000 2018 i7-8750H  开启触摸板GPIO失败
下面是SetGPIO_Original.txt
#************************************************************************************
Insyde H2OUVE (UEFI Variable Editor) Version 200.00.01.00
Copyright (c) 2012 - 2018, Insyde Software Corp. All Rights Reserved.

#************************************************************************************
#  Please follow file format to modify variable information.
#
#  File Format:
#
#   [Index] Variable Name
#          GUID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
#          Attributes: 0xXX
#          DataSize: 0xXX
#          Data:
#                00000000: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX 
#                00000010: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX 
#                 .....                         .....
#  
#  1. Index is a number in Hex.
#  2. The number of data must be equal to datasize.(Except datasize = 0)
#  3. "X") represents a hex number.
#
#  Delete Variable:
#    Please modify datasize or Attributes value to zero.
#
#************************************************************************************

 [001] "PchSetup"
      GUID: 4570B7F1-ADE8-4943-8DC3-406472842384
      Attributes: 0x7
      DataSize: 0x6DB
      Data:
            00000000: 00 00 C4 3E 00 01 00 00 00 01 02 00 01 01 00 00 
            00000010: 01 01 02 03 00 00 01 01 00 00 00 01 00 01 01 FF 
            00000020: 01 00 00 00 01 01 01 01 00 01 00 00 00 00 00 00 
            00000030: 00 01 00 00 01 01 01 01 00 00 00 00 00 00 00 01 
            00000040: 01 00 00 01 00 00 01 01 01 01 01 01 01 01 00 00 
            00000050: 00 00 00 00 00 00 01 01 01 01 01 01 01 01 00 00 
            00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 
            00000080: 01 01 01 01 01 01 01 01 00 00 00 01 01 00 01 00 
            00000090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000000A0: 71 02 71 02 71 02 71 02 71 02 71 02 71 02 71 02 
            000000B0: 0F 0F 0F 0F 0F 0F 0F 0F 00 00 00 00 00 00 00 00 
            000000C0: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000000D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000000E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000000F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 
            00000100: 01 01 01 01 00 00 01 00 00 00 00 00 00 00 04 04 
            00000110: 04 04 04 04 04 04 04 04 04 04 04 04 04 04 04 04 
            00000120: 04 04 04 04 04 04 00 00 00 00 00 00 00 00 00 00 
            00000130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000140: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000001F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 
            00000200: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            00000210: 01 01 01 01 01 01 00 00 00 00 00 00 00 00 00 00 
            00000220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 
            00000230: 01 01 01 01 01 01 01 01 01 01 00 01 01 01 01 01 
            00000240: 01 01 01 01 01 01 00 00 00 00 00 00 00 00 00 00 
            00000250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000270: 00 00 00 00 00 00 02 02 02 02 02 02 02 02 02 02 
            00000280: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 01 01 
            00000290: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002A0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002B0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002C0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002D0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002E0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            000002F0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            00000300: 01 01 01 01 01 01 05 05 05 05 05 05 05 05 05 05 
            00000310: 05 05 05 05 05 05 05 05 05 05 05 05 05 05 07 07 
            00000320: 07 07 07 07 07 07 07 07 07 07 07 07 07 07 07 07 
            00000330: 07 07 07 07 07 07 06 06 06 06 06 06 06 06 06 06 
            00000340: 06 06 06 06 06 06 06 06 06 06 00 00 00 00 02 02 
            00000350: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000360: 02 02 00 00 00 00 05 05 05 05 05 05 05 05 05 05 
            00000370: 05 05 05 05 05 05 05 05 05 05 05 05 05 05 01 01 
            00000380: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            00000390: 01 01 01 01 01 01 00 00 00 00 00 00 00 00 00 00 
            000003A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000003B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000003C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000003D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000003E0: 04 06 08 0A 0C 08 02 06 08 02 00 00 00 01 01 01 
            000003F0: 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 
            00000400: 01 01 01 01 01 01 00 00 00 00 00 00 00 00 00 00 
            00000410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 02 
            00000420: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000430: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000440: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000450: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000460: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 02 
            00000470: 02 02 02 02 02 02 02 02 02 02 02 02 02 02 3C 00 
            00000480: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 
            00000490: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 
            000004A0: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 
            000004B0: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 
            000004C0: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 
            000004D0: 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 3C 00 00 00 
            000004E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000004F0: 00 00 00 00 00 00 04 00 00 00 00 00 00 00 00 00 
            00000500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0A 
            00000510: 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 
            00000520: 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 
            00000530: 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 0A 00 04 
            00000540: 04 04 04 04 04 04 04 04 04 04 04 04 04 04 04 04 
            00000550: 04 04 04 04 04 04 04 01 00 00 01 00 00 01 01 01 
            00000560: 00 00 00 00 00 00 00 00 00 00 02 04 00 00 00 00 
            00000570: 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            000005F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000630: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
            00000670: 00 00 00 00 00 00 00 00 00 00 00 01 01 01 01 01 
            00000680: 00 00 00 00 00 00 01 01 00 01 01 01 01 01 01 01 
            00000690: 00 00 00 00 01 01 00 00 01 00 00 00 00 01 00 00 
            000006A0: 00 00 0E 00 00 00 00 01 00 01 01 01 00 03 03 01 
            000006B0: 00 00 00 00 00 00 00 00 00 01 03 02 01 00 00 01 
            000006C0: 01 02 03 00 00 00 01 02 03 00 00 00 01 00 00 01 
            000006D0: 00 01 01 00 00 00 00 00 01 00 01

**Comment by xiaoMGitHub** [comment]
或者你可以联系脚本开发者

**Comment by alexlipe** [comment]
联系了作者, 说是等后续更新. 我从BIOS高级模式中找到对应的选项. 手动开启了
