### ISSUE TITLE
update from 10.15.0 to 10.15.4

### ISSUE THREAD

**Issue by deounix** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#75]
I've lenovo legion y530 I install this release 3.0.1 and it works 100% but can I update mac to latest version (10.15.4) ?

**Comment by deounix** [comment]
because I tried to update and it stuck on mac apple logo

**Comment by theMonk3y** [comment]
Hey bro! Update your clover and kexts to the latest version and boot to the clover and run the partiton - data.

[MY EFI - CATALINA VERSION 10.15.5](https://mega.nz/file/x5wHCLzT#Y7bHZUVKP49q7vG7qvT7HC8wgP5zFMJgi5p5aF8ESl0)

**Comment by xiaoMGitHub** [comment]
[3.0.2 ](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2)EFI has been uploaded.

**Comment by ucristian3** [comment]
> [3.0.2 ](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2)EFI has been uploaded.

Tried the opencore build 
Audio is working (appleHDA kext)
My DW1820A is also working perfectly

**Comment by theMonk3y** [comment]
> [3.0.2 ](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2)EFI has been uploaded.

After replace 3.0.2 (oc) I lost my windows boot option .
I have installed on separate ssd windows for dual boot. 😅
Any solution?

**Comment by ucristian3** [comment]
> > [3.0.2 ](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2)EFI has been uploaded.
> 
> After replace 3.0.2 (oc) I lost my windows boot option .
> I have installed on separate ssd windows for dual boot. 😅
> Any solution?

You have to restore EFI partition 
you can try to use this tutorial here.
https://www.ubackup.com/windows-10/restore-efi-partition-windows-10-8523.html

**Comment by theMonk3y** [comment]
> > > [3.0.2 ](https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh/releases/tag/v3.0.2)EFI has been uploaded.
> > 
> > 
> > After replace 3.0.2 (oc) I lost my windows boot option .
> > I have installed on separate ssd windows for dual boot. 😅
> > Any solution?
> 
> You have to restore EFI partition
> you can try to use this tutorial here.
> https://www.ubackup.com/windows-10/restore-efi-partition-windows-10-8523.html

nop. dosent help. 
but when i put back the version 3.0.1 everything is normal. i replace again to 3.0.2 and windows again hidden.

**Comment by xiaoMGitHub** [comment]
Create one more ESP partition and store boot files of different systems separately.
