### ISSUE TITLE
Jack audio stopped working

### ISSUE THREAD

**Issue by TheSenseiRyu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#77]
Hi, ive just updated to 3,2 efi and everything work exept audio when i plug jack headphones...when i plug it it sound super weird and crap. Its the same for opencore and clover, i tried to reboot, to run the script but nothing work. The sound without jack plugged is great, i think that its an issue with alcplugfix but dont know what. It allways work perfectly on my pc. I dont have a backup of 3.1 efi so i could not try to backup my older one.
My pc is lenovo legion y540 irh i5 9e gen, 16gb ram, rtx 2060 on macos 10.14.6

**Comment by xiaoMGitHub** [comment]
It is recommended to use iPhone headphones.

**Comment by TheSenseiRyu** [comment]
I do

**Comment by TheSenseiRyu** [comment]
I was on Mojave, i updated to catalin, re run the script and everything now run ok

**Comment by xiaoMGitHub** [comment]
This is an interesting problem. Under normal circumstances, to ensure that the script is executed successfully, most of the problems are solved.

**Comment by TheSenseiRyu** [comment]
Yes, and it solved my reboots problems too. I dont know what have changed. I had installed macos clean, vanilla and clover you post unmodified. But now its working great, my laptop was in sleep all the night and open almost instant that morning. On the other side, open core is working but only if u push the command+option+p+r at every reboot. Thx a lot for all your hard work, i really appreciate a lot( if you have a paypal iwould be glad to donate). I can use it at home with powerful rtx and windows and for studying on mac. Oh and i use volta too, to reduce battery usage. It work super great and really improve the time without charging. I know this is base on a github script maybe i could be integrated to your efi ? Sorry its not really the appropriate place for all that stuff but i did’t know where to put it ^^
