### ISSUE TITLE
How to Enable Nvidia on High Sierra 10.13.6 (Lenovo Y530)

### ISSUE THREAD

**Issue by FC2714** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#78]
I have successfully installed 10.13.6 to my Lenovo y530 with your EFI 3.0.1 . I have also downloaded and installed Nvidia web and Cuda drivers they are also installed successfully. But I can not enable GPU of Nvidia to make it recognizable by drivers. 
how can I do that? what modifications should I do?
I tried nada_drv=1 putting checkbox to Nvidiaweb  tried to disable IGPU (only got 7mb but still UHD graphics)

**Comment by xiaoMGitHub** [comment]
Do not buy Lenovo notebooks next time, basically you can't drive Nvidia card.

**Comment by FC2714** [comment]
This is 100% ? Because in some cases I have seen on internet on high sierra
people can activate nvidia 1000 series. But by your saying I assume that On
Lenovo notebooks it is 100% impossible to activate it even on nvidia
supported mac OS?  Or there is a chance by somehow modifying something like
ssdt or kext or config etc

**Comment by xiaoMGitHub** [comment]
Some thinkpad models can be driven, such as P71.
