### ISSUE TITLE
Is the discrete GPU disabled

### ISSUE THREAD

**Issue by TheSenseiRyu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#79]
I was asking myself, is the nvidia fully disabled or is it running silently sucking power ? 

edit: is that thing is done or have i to do it?
https://www.tonymacx86.com/threads/guide-disabling-discrete-graphics-in-dual-gpu-laptops.163772/

**Comment by dlhxr** [comment]
disabled as no way to support NVIDIA here.
