### ISSUE TITLE
2018 y7000 mac 10.15.14/13睡眠重启,能给看看啥问题么

### ISSUE THREAD

**Issue by gzz8898** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#80]
mp_kdp_enter() timed-out on cpu 2, NMI-ing
mp_kdp_enter() NMI pending on cpus: 0
mp_kdp_enter() timed-out during locked wait after NMI;expected 12 acks but received 11 after 10164622 loops in 1104000000 ticks
panic(cpu 2 caller 0xffffff801704c32a): Kernel trap at 0xffffff8017063d9e, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x00000110179ef898, CR3: 0x000000002bf94000, CR4: 0x00000000003626e0
RAX: 0x0000018ffffffe70, RBX: 0x0000000000001d51, RCX: 0x0000000000000000, RDX: 0xffffff80179efa20
RSP: 0xffffff82c1e13d70, RBP: 0xffffff82c1e13e20, RSI: 0x0000000000000000, RDI: 0x00000000ffffffff
R8:  0x0000000000000000, R9:  0x0000000000000680, R10: 0x00000000001776af, R11: 0xffffff80179f5280
R12: 0xffffffffeede8358, R13: 0x00000000000057f3, R14: 0xffffff80179f0380, R15: 0x0000000000000006
RFL: 0x0000000000010002, RIP: 0xffffff8017063d9e, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000110179ef898, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 1, VF: 5

Backtrace (CPU 2), Frame : Return Address
0xffffff82c1e137d0 : 0xffffff8016f215cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff82c1e13820 : 0xffffff801705a3c5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff82c1e13860 : 0xffffff801704bf7e mach_kernel : _kernel_trap + 0x4ee
0xffffff82c1e138b0 : 0xffffff8016ec7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff82c1e138d0 : 0xffffff8016f20c97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff82c1e139d0 : 0xffffff8016f21087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff82c1e13a20 : 0xffffff80176c2c7c mach_kernel : _panic + 0x54
0xffffff82c1e13a90 : 0xffffff801704c32a mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff82c1e13c10 : 0xffffff801704c028 mach_kernel : _kernel_trap + 0x598
0xffffff82c1e13c60 : 0xffffff8016ec7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff82c1e13c80 : 0xffffff8017063d9e mach_kernel : _xcpm_urgency + 0x66e
0xffffff82c1e13e20 : 0xffffff801704e64e mach_kernel : _thread_tell_urgency + 0x8e
0xffffff82c1e13e70 : 0xffffff8016f43deb mach_kernel : _thread_dispatch + 0x5ab
0xffffff82c1e13ed0 : 0xffffff8016f4370b mach_kernel : _thread_unstop + 0x1a4b
0xffffff82c1e13f40 : 0xffffff8016f45035 mach_kernel : _thread_run + 0x35
0xffffff82c1e13f80 : 0xffffff8016f468bb mach_kernel : _idle_thread + 0x7b
0xffffff82c1e13fa0 : 0xffffff8016ec713e mach_kernel : _call_continuation + 0x2e

BSD process name corresponding to current thread: kernel_task
Boot args: dart=0 keepsyms=1 

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000016c00000
Kernel text base: 0xffffff8016e00000
__HIB  text base: 0xffffff8016d00000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 198183870442
last loaded kext at 8045217301: >AudioAUUC	1.70 (addr 0xffffff7f99b5c000, size 32768)
loaded kexts:
(none)

**Comment by xiaoMGitHub** [comment]
刷次BIOS就好了，或者尝试使用一键修改BIOS脚本（耐心等待群主发布正式版）

**Comment by gzz8898** [comment]
好的，静静地等待

**Comment by gzz8898** [comment]
> 刷次BIOS就好了，或者尝试使用一键修改BIOS脚本（耐心等待群主发布正式版）

好的，静静滴等待

**Comment by gzz8898** [comment]
更新了一下最新bios，貌似好了，用用看吧

**Comment by gzz8898** [comment]
更新了一下bios,貌似好了，先用用看了
