### ISSUE TITLE
any way to get 3fingers gesture on y540 irh ?

### ISSUE THREAD

**Issue by TheSenseiRyu** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#81]
i searched a long time today and tried a bunch of stuff but not find anything working. I was asking myself : is there a way to get 100% working on my touchpad  Actually i use your latest public efi and ive no 3fingers and right click. Are you planning in the future to look at taht or its dead and ive to do with what i have ? Last thing, can i buy on ebay a compatible touchpad like the synaptic one and replace my existing one with it ? Thanks in advance for an reply, have a good day.

**Comment by xiaoMGitHub** [comment]
Provide your touchpad model.

**Comment by TheSenseiRyu** [comment]
I have the intel 2ic one

**Comment by xiaoMGitHub** [comment]
Some models of touchpads are not fully functional, and there is currently no solution. It is recommended to consult [alexandred](https://github.com/alexandred/VoodooI2C/issues).

**Comment by TheSenseiRyu** [comment]
Yes, thats what i could find too. A really big thx for your reply a new time. Have a nice day.
