### ISSUE TITLE
睡眠后发热严重直至电量耗尽关机

### ISSUE THREAD

**Issue by AlwaysZmx** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#83]
型号：Y7000 2019 PG0 1650/8G 手动点击睡眠后，合上屏幕，过了一个多小时，发现电脑很烫，而且电量已经耗尽无法开机。用的EFI版本为3.0.2，Mac OS版本10.15.4，系统是全新完整安装的，非升级

**Comment by xiaoMGitHub** [comment]
刷次BIOS

**Comment by Mr-UFO** [comment]
@AlwaysZmx 换oc

**Comment by Mr-UFO** [comment]
#62

**Comment by AlwaysZmx** [comment]
> 刷次BIOS

@Mr-UFO 说睡眠问题是colver的通病，这个问题可以通过刷bios解决吗？如果可以的话我想尝试一下

**Comment by Mr-UFO** [comment]
@AlwaysZmx 试试呗，还不行的话就换oc
