### ISSUE TITLE
Y540-15IRH with i7

### ISSUE THREAD

**Issue by epalzeolithe** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#84]
Hi 

you did a great work !

i'm in 10.15.4 with opencore 0.5.8, but few things is not working :
- the computer becomes choppy after sleep
(trackpad is not working and  numpad is not working - of course I use the script post-install)

here's my config :
Y540-15IRH, with i7 9750h on HM370, with RTX2060 and iGPU 630UHD

do i have to add few kext ? it seems to be a matter of CPU power management failing

Thx in advance :) :)

**Comment by epalzeolithe** [comment]
Well fixed. Changing few kexts. Guessing which one

**Comment by xiaoMGitHub** [comment]
I have not released an EFI based on OC 0.5.8, please look forward to the next update.

**Comment by epalzeolithe** [comment]
Hi

thank you so much :) :) :)

I switch to 0.5.7, now booting and sleep correctly with the right kexts.

What I' don't understand is why trackpad is working under clover, and not OpenCore.

by the way you did a so GREAT job :) :)

**Comment by epalzeolithe** [comment]
Working ;à) I was using old AML, so the GPIO was not corrected I think. trackpad is now working except buttons :)

**Comment by guillerpsanchez** [comment]
> Hi
> 
> thank you so much :) :) :)
> 
> I switch to 0.5.7, now booting and sleep correctly with the right kexts.
> 
> What I' don't understand is why trackpad is working under clover, and not OpenCore.
> 
> by the way you did a so GREAT job :) :)

Could you share your efi folder please.

Thank you in advance.

**Comment by xiaoMGitHub** [comment]
There will be a big update soon.

**Comment by HasanAlyazidi** [comment]
> 
> 
> Working ;à) I was using old AML, so the GPIO was not corrected I think. trackpad is now working except buttons :)

Can you share your `EF`I folder please? Thank you in advance.
