### ISSUE TITLE
HDMI on USB-C

### ISSUE THREAD

**Issue by epalzeolithe** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#87]
HI 

i tried to assign GPU HD630 to USB-C on Y540 with HD630 and RTX2060,

I patched the framebuffer to 306, 204, 105 connectors.

No way to attach the HD630 to USB-C. It seems that non onlu the HDMI connector is only connected to RTX2060, but USB-C too :(

**Comment by xiaoMGitHub** [comment]
HDMI port is connected with disabled NVIDIA DGPU
