### ISSUE TITLE
Y7000-2019更换40pin屏线换上144hz屏幕后，卡在ioconsoleusers

### ISSUE THREAD

**Issue by countlessLollipops** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#88]
40pin屏线型号DC02C00FC10，144hz屏幕型号LGD LP156WFG-SPF3
开机卡在IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
跑码到这里屏幕背光亮度下降了一点。

原本的30pin屏线和60hz屏幕BOE NV156FHM-N61，正常开机，正常使用。

**Comment by xiaoMGitHub** [comment]
应该是config的设置问题吧，可以加群去咨询下群主

**Comment by imesh17** [comment]
> 40pin screen cable model DC02C00FC10, 144hz screen model LGD LP156WFG-SPF3
> boot stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> here the backlight brightness of the screen has dropped a little.
> 
> The original 30pin screen cable and 60hz screen BOE NV156FHM-N61 are turned on normally and used normally.

add this to your displayproperties - 

			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>enable-dpcd-max-link-rate-fix</key>
				<data>AQAAAA==</data>
				<key>dpcd-max-link-rate</key>
				<data>CgAAAA==</data>
			</dict>

**Comment by countlessLollipops** [comment]
> > 40pin screen cable model DC02C00FC10, 144hz screen model LGD LP156WFG-SPF3
> > boot stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> > here the backlight brightness of the screen has dropped a little.
> > The original 30pin screen cable and 60hz screen BOE NV156FHM-N61 are turned on normally and used normally.
> 
> add this to your displayproperties -
> 
> ```
> 		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> 		<dict>
> 			<key>enable-dpcd-max-link-rate-fix</key>
> 			<data>AQAAAA==</data>
> 			<key>dpcd-max-link-rate</key>
> 			<data>CgAAAA==</data>
> 		</dict>
> ```

Thanks, I've fixed this issue a few days ago. The solution is the same as yours.

**Comment by imesh17** [comment]
> > > 40pin screen cable model DC02C00FC10, 144hz screen model LGD LP156WFG-SPF3
> > > boot stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> > > here the backlight brightness of the screen has dropped a little.
> > > The original 30pin screen cable and 60hz screen BOE NV156FHM-N61 are turned on normally and used normally.
> > 
> > add this to your displayproperties -
> > 
> > ```
> > 		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> > 		<dict>
> > 			<key>enable-dpcd-max-link-rate-fix</key>
> > 			<data>AQAAAA==</data>
> > 			<key>dpcd-max-link-rate</key>
> > 			<data>CgAAAA==</data>
> > 		</dict>
> > ```
> 
> Thanks, I've fixed this issue a few days ago. The solution is the same as yours. 

Do you've any other issues with this panel in macos? Like changing resolution , maybe sleep/wake issues . I've the exact same panel in my laptop.

**Comment by countlessLollipops** [comment]
> > > > 40pin screen cable model DC02C00FC10, 144hz screen model LGD LP156WFG-SPF3
> > > > boot stuck at IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
> > > > here the backlight brightness of the screen has dropped a little.
> > > > The original 30pin screen cable and 60hz screen BOE NV156FHM-N61 are turned on normally and used normally.
> > > 
> > > 
> > > add this to your displayproperties -
> > > ```
> > > 		<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
> > > 		<dict>
> > > 			<key>enable-dpcd-max-link-rate-fix</key>
> > > 			<data>AQAAAA==</data>
> > > 			<key>dpcd-max-link-rate</key>
> > > 			<data>CgAAAA==</data>
> > > 		</dict>
> > > ```
> > 
> > 
> > Thanks, I've fixed this issue a few days ago. The solution is the same as yours.
> 
> Do you've any other issues with this panel in macos? Like changing resolution , maybe sleep/wake issues . I've the exact same panel in my laptop.

So far, I haven't noticed anything wrong with the screen. But I have never tried opening HIDPI.
