### ISSUE TITLE
Poor benchmark score

### ISSUE THREAD

**Issue by ucristian3** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#89]
Hello , 
In Windows I get very different results compared to Mac and it doesn't matter if I'm using opencore or clover. How can I fix this behavior?

Spec:
Y540 i5 9300h + gtx1660ti 

 Geekbench 5   Mac: 980 3900
                           Win : 1100 4600
 Cinebench r20 Mac : 1800
                            Win: 2115

**Comment by quanddo** [comment]
I had similar low score with geekbench 4 -

win: 53XX 23XXX range
mac: 46XX 20XXX range

Using intel power gadget, I saw that the turbo boost frequency maxed out around 3.8ghz for single core, and multicore at 3.2-3ghz. Whereas on windows, it was 4.3ghz and 3.7ghz.

I played around with setting different SMBIOS, I finally arrived at an iMac19,2 model real mac with i7-8700 CPU with 6-core TB up to 4.6ghz. Now I can see similar turbo boost profile as when it was on windows, GB4 score now at 54XX and 23XXX.

Look at the OpenCore desktop guide for Coffee Lake, you'll find the util to generate the SMBIOS serial and system UUID for iMac19,2.
