### ISSUE TITLE
网卡

### ISSUE THREAD

**Issue by sailcat-code** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#93]
请问一下，不推荐使用DW1820A的话可以用什么网卡呢？谢谢

**Comment by xiaoMGitHub** [comment]
可以使用1560、1830、白果卡都是很好的选择，总之别选1820A这种垃圾

**Comment by Code-God1024** [comment]
Intel无线网卡可以了，详见远景

**Comment by NinelieZ** [comment]
> Intel无线网卡可以了，详见远景

那个网卡驱动还不够易用吧

**Comment by Code-God1024** [comment]
> > Intel无线网卡可以了，详见远景
> 
> 那个网卡驱动还不够易用吧

勉强可以，差不多了，等大佬做出客户端

**Comment by sailcat-code** [comment]
谢谢大佬

**Comment by sailcat-code** [comment]
小白顺便问一下，下载之后的zip文件是怎么用呢？是直接把整个文件夹复制吗？

**Comment by xiaoMGitHub** [comment]
只推荐1560、1830、白果卡
