### ISSUE TITLE
HDMI问题

### ISSUE THREAD

**Issue by Code-God1024** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#94]
拯救者Y7000我现在装的10.14系统，不支持HDMI，我换到13系统可以用HDMI吗

**Comment by xiaoMGitHub** [comment]
不能正常使用的功能
HDMI ，因为HDMI 端口连接到已禁用的Nvidia卡

**Comment by Code-God1024** [comment]
> 不能正常使用的功能
> HDMI ，因为HDMI 端口连接到已禁用的Nvidia卡

10.13系统用Web Driver装N卡驱动也不行吗

**Comment by xiaoMGitHub** [comment]
建议多尝试

**Comment by Code-God1024** [comment]
> 建议多尝试

Ok，等会我试一试
