### ISSUE TITLE
Y740 Support & IOUSBHostHIDDevice error

### ISSUE THREAD

**Issue by HasanAlyazidi** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#95]
Hello,

Any plans for supporting Lenovo Legion Y740?

I tried installing Catalina 10.15.5 using your EFI 3.0.2 & 3.0.3 with no success.

I get the following kernel panic

"IOUSBHostHIDDevice::interruptReadComplete: IO error 0xe00002ed"

![Error](https://user-images.githubusercontent.com/7901330/84657551-bb038c00-af14-11ea-8d52-4d0cc35dc94e.jpeg)

My laptop specs:
Lenovo Legion Y740-15IRHg
CPU: i7-9750h
RAM: 16GB
GPU: nVidia RTX 2060, Intel UHD 630

All USB ports are USB3.0 and 3.1, one Type-C with Thunderbolt 3. RGB keyboard.

Thank you in advance

**Comment by xiaoMGitHub** [comment]
Clover：
Remove USB port restrictions
```
Comment: USB port limit patch 
Name: com.apple.iokit.IOUSBHostFamily
Find: 83FB0F0F
Replace: 83FB3F0F

Comment: USB Port limit patch 
Name: com.apple.driver.usb.AppleUSBXHCI
Find: 83F90F0F
Replace: 83F93F0F
```
Add [driver ](https://github.com/Sniki/OS-X-USB-Inject-All/releases)to EFI/CLOVER/kexts/Other

**Comment by HasanAlyazidi** [comment]
I have added USB Port limit patch as follows

![image](https://user-images.githubusercontent.com/7901330/84769756-a38cd780-afd6-11ea-823e-94aaa480b1ae.png)

Is it correct?

Anyway , the following error occurred after adding the patch:
![image](https://user-images.githubusercontent.com/7901330/84770399-c9ff4280-afd7-11ea-9038-a930c3647b84.png)




Can I use OpenCore instead of Clover?

The error

`IOUSBHostHIDDevice::interruptReadComplete: IO error 0xe00002ed`

occurs on both. 


Thank you

**Comment by xiaoMGitHub** [comment]
There may be a problem with your EFI configuration, it is recommended to check carefully.

**Comment by HasanAlyazidi** [comment]
I just used your EFI v3.0.3

**Comment by xiaoMGitHub** [comment]
My EFI only supports y530/y540/y545, y740 is not supported.

**Comment by HasanAlyazidi** [comment]
How can i reach you for a paid support service?
