### ISSUE TITLE
Auto Restart when try to install hackintosh on SSD Samsung PM981 256GB NVMe  ?

### ISSUE THREAD

**Issue by yasserdhia** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#96]
Hi Bro , i want to ask about the  SSD Samsung PM981 256GB NVMe can't install Catalina macos and its auto restart when try to install on SSD , but when try to install on HDD its working . i have LAPTOP Lenovo Y530 , can i fixed that with some kext or drivers or not .. thanks friend again.

**Comment by xiaoMGitHub** [comment]
Samsung PM981 does not support the installation of hackintosh, it is recommended to replace other SSD.

**Comment by yasserdhia** [comment]
Thanks friend for fast reply 😍.. What type of SSD recommendation stable  that support lenovo y530 and hackintosh ? Thanks again .

**Comment by xiaoMGitHub** [comment]
intel 760P

**Comment by yasserdhia** [comment]
My friend .. If i want to convert SSD Samsung PM981 to external hard drive and connect with usb and install hackintosh on external SSD PM981 . Is that working or not? Sorry about more questions , thanks agian bro ^_^.
