### ISSUE TITLE
Y7000更新3.0.2后的问题

### ISSUE THREAD

**Issue by cqlhupt** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#97]
2018 i7-1050ti 2T，win10，Ubuntu，mojave三系统更新3.0.2后clover界面中win10的图标不见了，但是我看见图标资源还在
![screenshot0](https://user-images.githubusercontent.com/44506040/85044346-0f7e6400-b1c0-11ea-8581-f6d25ef986f8.png)

**Comment by xiaoMGitHub** [comment]
图标适配问题，最新的EFI已经重新绘制图标，期待下次的更新
