### ISSUE TITLE
有y9000k 2020 款的支持嘛？想问下怎么驱动10875h的核显

### ISSUE THREAD

**Issue by MrCloudyGod** [xiaoMGitHub/LEGION_Y7000Series_Hackintosh#98]
查到的10750h和10875h 核显id通用，但是看了一下这个efi里好像platform-id并不一样啊

**Comment by xiaoMGitHub** [comment]
你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动

**Comment by sailcat-code** [comment]
Y7000P 2020 最近也上八核CPU了，有没有支持的计划呢？

**Comment by xiaoMGitHub** [comment]
> Y7000P 2020 最近也上八核CPU了，有没有支持的计划呢？

期待有缘人提供测试设备

**Comment by Yeah2333** [comment]
我可以提供Y9000K 2020的测试支持，老哥有想法吗

**Comment by MrCloudyGod** [comment]
> 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动

感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版

**Comment by xiaoMGitHub** [comment]
> > 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动
> 
> 感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版

大部分热补丁是通用的，OC版本等多端时间OSX11稳定了就会更新

**Comment by xiaoMGitHub** [comment]
> > > 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动
> > 
> > 
> > 感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版
> 
> 大部分热补丁是通用的，OC版本等多端时间OSX11稳定了就会更新

请问你的声卡能驱动不？昨天装了一台2020款y9000k国际版，似乎声卡无法驱动

**Comment by xiaoMGitHub** [comment]
> > > 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动
> > 
> > 
> > 感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版
> 
> 大部分热补丁是通用的，OC版本等多端时间OSX11稳定了就会更新

请问你的声卡能驱动不？昨天装了一台2020款y9000k国际版，似乎声卡无法驱动

**Comment by MrCloudyGod** [comment]
> > > > 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动
> > > 
> > > 
> > > 感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版
> > 
> > 
> > 大部分热补丁是通用的，OC版本等多端时间OSX11稳定了就会更新
> 
> 请问你的声卡能驱动不？昨天装了一台2020款y9000k国际版，似乎声卡无法驱动

最近没有时间搞啊驱动了核显就放那了……是外放没声吗？有没有试过耳机孔或者USB音箱…apple alc如果显示驱动了但是外放没声的话，估计问题又在机器自身硬件的声音放大器那里，类似目前y9000x的外放无解

**Comment by xiaoMGitHub** [comment]
> > > > > 你可以使用2020款的配置文件进行尝试，理论上2020款y9000k搭载的10750H和2020款y7000/P是同一个U，应该一样能被驱动
> > > > 
> > > > 
> > > > 感谢！使用了2020 y7000p这个config成功进入并驱动了9000k核显，就是苹果logo加载阶段会有一次变色闪屏。另外acpi里那些补丁应该就不适用了吧，我没放进去。期待oc版
> > > 
> > > 
> > > 大部分热补丁是通用的，OC版本等多端时间OSX11稳定了就会更新
> > 
> > 
> > 请问你的声卡能驱动不？昨天装了一台2020款y9000k国际版，似乎声卡无法驱动
> 
> 最近没有时间搞啊驱动了核显就放那了……是外放没声吗？有没有试过耳机孔或者USB音箱…apple alc如果显示驱动了但是外放没声的话，估计问题又在机器自身硬件的声音放大器那里，类似目前y9000x的外放无解

目前情况应该是跟y9000x一样，机友测试在linux下无外放
